boostcampwm-2022/web19-Boostart

- server/package-lock.json
- server/package.json
> [BE] Update Dependencies

- client/src/App.tsx
- client/src/pages/MainPage.tsx
- client/src/pages/WelcomePage.tsx
- client/src/routes/PrivateRoute.tsx
- client/src/routes/RestrictedRoute.tsx
로그인 권한 route 설정
생략
로그인 안하고 main 접근 시 로그인 화면으로 redirect
로그인 하고 / 접근 시 main 화면으로 redirect
1. Private route 구현
2. Restricted Route 구현
> [FE] 공통 - 로그인 권한 private route 설정

- server/src/api/auth.ts
- server/src/app.ts
- server/src/constants/index.ts
- server/src/utils/auth.ts
- server/src/utils/validate.ts
신규 유저를 검증하고 DB에 추가하는 API를 작성했습니다.
[birdeatsbug](https://app.birdeatsbug.com/sessions/A-CIWLuk3qSKdtTIujBtSURGA8KMW9XY2HdvoyB67opM)
1. API를 작성했습니다.
2. 테스트 코드를 작성했습니다. (커밋에 포함X)
```
const response = await fetch(`${HOST}/api/v1/auth/signup`, {
headers: { 'Content-Type': 'application/json' },
userId: id,
password: pw,
username: name,
}),
});
console.log(response);
const result = await response.json();
console.log(result);
```
- https://github.com/boostcampwm-2022/web19-Boostart/issues/11
- `Content-Type`이 `application/json`이어야 합니다.
- 이미지 업로드 미구현 상태입니다. (프론트엔드 연결 후 작업 예정)
- 유효성 검증 절차를 개선해야 합니다.
- 필드가 비어있는지
- 닉네임이 중복인지
- 이미 회원가입되어 있는 계정인지
> [BE] 회원가입 API

- client/package-lock.json
- client/package.json
state의 개수를 줄이고, 프론트엔드 단 입력값 검증을 돕기 위해 다음 라이브러리들을 설치했습니다.
- react-hook-form
- yup
- @hookform-resolvers
> [FE] Update dependencies

- client/src/components/MainPage/TaskModal/ImportanceInput/index.tsx
`ImportanceInput` 컴포넌트의 로직을 간소화했습니다
> [FE] [7-14] 컴포넌트 간소화

- client/src/components/MainPage/MainContents/Log/TaskItem.tsx
- client/src/components/MainPage/MainContents/Log/style.ts
백로그 [7-3] 완료된 task 배경색 변경 로직
1. task data 중 완료상태를 boolean으로 나타내는 done 값에 따라 배경색을 변경했습니다
- 7-3
> feat: [7-3] 완료된 task 배경색 변경

- client/src/components/WelcomePage/LoginMenu/index.tsx
- server/src/api/auth.ts
서버의 상태를 클라이언트 화면에 표시하기 용이하도록 응답에 에러 메세지를 추가했습니다.
> [FE/BE] 로그인 응답 에러 메세지 추가

- client/package-lock.json
- client/package.json
전역상태로 관리할 날짜 관리를 위해 recoil install 했습니다
없다면 생략
1. recoil install
-
> [FE]Update dependencies

- server/src/api/auth.ts
로그인한 사용자의 쿠키를 삭제합니다.
1. 로그인을 완료하세요
2. 주소창에 `http://localhost:8000/api/v1/auth/logout`을 입력하세요.
3. 페이지를 새로고침하세요.
> [BE] [4-3] 로그아웃 API

- server/src/api/user.ts
로그인한 클라이언트가 자신의 사용자 이름, 아이디, 프로필 이미지를 조회할 수 있습니다.
1. 로그인을 완료하세요
2. 주소창에 `http://localhost:8000/api/v1/user/me`를 입력하세요.
> [BE] [4-17] 내 정보 조회 API

- server/app.ts
- server/src/api/friend.ts
친구 요청을 수락 및 거절하는 API를 구현하였습니다.
- 요청 URL : `/friend/accept/:user_idx`
- `user_idx` : 수락하고 싶은 친구 요청의 전송자
- method : `PATCH`
- 응답
- 친구 요청 수락 : `200`
- 존재하지 않는 친구 요청에 대한 실행 : `404`
- 요청 URL : `/friend/accept/:user_idx`
- `user_idx` : 거절하고 싶은 친구 요청의 전송자
- 응답
- 친구 요청 수락 : `200`
- 존재하지 않는 친구 요청에 대한 실행 : `404`
1. `/friend/request`를 통해 `user_idx = 29` 사용자의 친구 요청을 확인
2. 친구 요청 거절
3. `/friend/request`를 통해 `user_idx = 29` 사용자의 친구 요청이 삭제되었음을 확인
4. `/friend`를 통해 `user_idx = 29` 사용자의 친구 요청이 승인되지 않았음을 확인
[504bf54f-0484-476f-ae45-9bf5b654166d.webm](https://user-images.githubusercontent.com/92143119/203630480-f6be46f6-2c0a-4866-9132-7d5eedbb14fb.webm)
1. `/friend/request`를 통해 `user_idx = 29` 사용자의 친구 요청을 확인
2. 친구 요청 수락
3. …
> [BE] [4-5] 친구 요청 수락, 거절 API 구현

- client/src/components/MainContainer/Calendar.tsx
- client/src/components/MainContainer/MenuSelector.tsx
메뉴를 한번 선택하면 계속 Bold체로 남아있는 버그가 있었는데 수정했습니다.
1. 버튼 하나씩을 분리시켜서 state를 따로 둔것이 문제였는데 각각의 버튼이 아닌 menuselector 전체를 분리해서 해결했습니다.
2. 해당과정에서 메뉴셀렉터는 다른 컴포넌트로 아예 분리를 시켰습니다.
1.calendar 하단 메뉴를 선택하여 font style이 변경되는지 확인한다.
- [20]
> [BugFix] [20] active 메뉴에 따른 fontStyle 적용 오류 수정

- server/src/api/emoticon.ts
- server/src/types/index.d.ts
태스크에 이모티콘을 전송하는 API를 구현하였습니다.
- 요청 URL : `/emoticon/task/:task_idx`
- `user_idx` : 수락하고 싶은 친구 요청의 전송자
- method : `PUT`
- body : `{ emoticon }`
- `emoticon` : 보내고 싶은 이모티콘의 index
- 응답
- 이모티콘 전송 성공 : `201`
- 올바르지 않은 형식의 요청 : `400`
- 존재하지 않는 태스크, 이모티콘에 대한 요청 : `404`
1. 존재하지 않는 `idx = 1000` 태스크에 대한 이모티콘 전송 요청
2. `404` 코드가 반환됨을 확인
3. 존재하지 않는 `idx = 30` 이모티콘에 대한 이모티콘 전송 요청
4. `404` 코드가 반환됨을 확인
5. body에 `emoticon` 정보가 없는 이모티콘 전송 요청
6. `400` 코드가 반환됨을 확인
[0e1a9769-b10a-4538-a607-da8cb50da11d.webm](https://user-images.githubusercontent.com/92143119/204089927-6693ecb9-3ee4-48ce-b933-0a865842d662.webm)
1. `/emoticon/task/14`를 통해 `idx = 14` 태스크의 이모티콘 목록을 확인
2. `idx = 14` 태스크에 `idx = 6` 이모티콘 전송 요청
3. `/emoticon/task/14`를 통해 이모티콘 전송이 성공하였음을 확인 …
> [BE] [7-13] 태스크 이모티콘 전송 API 구현

- server/src/api/task.ts
사용자가 요청을 통해 자신의 task의 완료 여부를 `false`에서 `true`로 변경할 수 있습니다.
1. 로그인을 완료하세요.
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/task/18', {
method: 'PATCH',
headers: {
},
done: true,
}),
}).then((res) => {
if (res.ok) console.log('GOOD');
});
```
- body가 잘못된 경우 → 400
- done 이외의 필드가 포함된 경우
- done 필드의 값을 `false`로 설정한 경우
- done 필드가 포함되지 않은 경우
- 이미 해당 task가 완료 상태인 경우 → 409
- 자신의 task가 아닌 경우 → 403
- 요청한 task가 존재하지 않는 경우 → 404
> [BE] [7-27] task 완료 API

- server/src/api/task.ts
> [BE] [28] task 수정 API에서 조건문이 잘못되어있던 점 수정

- client/src/components/MainContainer/Log.style.ts
- client/src/components/MainContainer/Log.tsx
이제 태스크 탭에서 자신의 태그를 확인할 수 있습니다.
1. 로그인을 완료하세요
> [FE] [7-33] Task 탭 태그 조회 API 연결

- server/src/api/task.ts
태스크 생성 시 태스크와 라벨의 관계가 등록되지 않는 버그를 수정하였습니다.
태스크 생성 전 입력된 값의 유효성을 검사하는 과정에서 입력된 라벨의 유효성을 검사하는 로직이 구현되지 않아 임시로 라벨의 유효성을 `false`로 처리하여 발생하던 문제였습니다.
입력된 라벨 정보의 유효성을 검사하는 로직을 구현하여 해당 버그를 수정하였습니다.
라벨 정보의 유효성 검사 로직은 다음과 같습니다.
- 입력된 라벨 정보가 배열인지 검사합니다.
- 배열이 아닌 정보(`undefined` 등)가 입력되면 default 값인 빈 배열을 `labels`의 값으로 설정합니다.
- 배열일 경우 다음 단계로 이동합니다.
- 배열의 각 요소에 `labelIdx`와 `amount`가 설정되었는지 검사합니다.
- 하나의 값이라도 설정되지 않았다면 `400` 코드를 반환합니다.
- 모든 값이 설정되어 있다면 다음 단계로 이동합니다.
- 각 라벨이 사용자의 라벨 목록에 포함되는지 검사합니다.
- 사용자의 라벨 목록에 존재하지 않는 라벨이 있다면 `404` 코드를 반환합니다.
추가로 이 과정에서 `location` 정보를 추가하고 유효성 검사 함수에서 에러 메시지와 타입을 설정하였습니다.
- 요청 URL : `/task`
- `Request Body` : `{ title!, importance, date!, startedAt!, endedAt!, lat, lng, location, isPublic, tagIdx, content, done, labels: [ { labelIdx,  amount } ] }` (뒤에 !를 붙인 항목은 필수 항목) …
> [BE] [32] 태스크 생성 API 수정

- client/src/index.css
> [FE] [36] 스크롤바 스타일링

- client/src/components/MainContainer/Log.tsx
- client/src/components/MainContainer/MainContainer.tsx
- client/src/components/TaskModal/ImportanceInput.tsx
- client/src/components/TaskModal/TaskModal.tsx
이제 UI를 통해 task를 생성할 수 있습니다.
1. API 연결
2. 컴포넌트 이동
- `TaskModal`
- `NewTaskButton`
1. 로그인을 완료하세요
2. FAB를 눌러 태스크 모달을 여세요.
3. 제목, 태그, 시작 시각, 종료 시각을 입력하고 `NEW TASK!` 버튼을 누르세요.
4. 생성한 태스크가 화면에 표시됩니다.
> [FE] [35] task 생성 모달 - API 연결

- server/src/api/label.ts
- https://github.com/boostcampwm-2022/web19-Boostart/pull/109
위 PR을 merge하는 과정에서 기존의 라벨 삭제 API가 삭제되어 다시 추가하였습니다.
API에 대한 부분은 아래 PR의 내용과 동일합니다.
- https://github.com/boostcampwm-2022/web19-Boostart/pull/101
1. 기존의 라벨 삭제 API 추가
- [37]
> [BE] [37] 라벨 삭제 API 추가

- client/src/components/Drawer/Drawer.tsx
- client/src/pages/MainPage.tsx
로그아웃버튼을 누르면 로그아웃하며 로그인페이지로 돌아갑니다.
없다면 생략
1.로그아웃버튼에 로그아웃 API를 연결하였습니다
2.로그아웃 성공시 root url로 리다이렉트합니다.
1.로그인한다.
2.우측상단 햄버거버튼을 누른다
3.열리는 drawer창에서 로그아웃버튼을 눌러 확인한다.
-[4-3]
> [FE] [4-3] 로그아웃기능 구현

- client/src/components/Drawer/Drawer.tsx
- client/src/pages/MainPage.tsx
Drawer 상단에 본인의 프로필에 정상적으로 표시됩니다.
없다면 생략
1. 친구Bar 구현시 불러왔던 myProfile을 drawer에도 넘겨줍니다.
2. 해당 정보를 바탕으로 본인 프로필을 표시합니다.
1.로그인한다.
2. 우측 상단 햄버거버튼을 누른다
3.확장되는 Drawer바에서 프로필을 확인한다
-[4-23]
> [FE] [4-23] 본인 프로필 확인 API 연결

- server/src/api/tag.ts
친구의 태그를 조회할 수 있는 API를 구현하였습니다.
친구인 사용자에 한해서만 태그를 조회할 수 있습니다.
- 요청 URL : `/tag/:user_id`
- `user_id` : 조회하고 싶은 친구의 id
- 응답
- `[ { idx, title, color, count } ]` (태그 객체 배열)
- 자신에 대한 요청 : `/tag`로 redirect 처리하여 자신의 태그를 조회하는 API 요청
- 친구가 아닌 사용자에 대한 요청 : `403`
- 존재하지 않는 사용자에 대한 요청 : `404`
1. 자신의 아이디 `pikachu`에 대한 요청인 `/tag/pikachu`을 통해 `/tag`로 redirect 처리되는 것을 확인
[76814029-017c-4d9b-bb35-a8ad59ea55a1.webm](https://user-images.githubusercontent.com/92143119/204968008-e0f23e4b-b740-4f3a-84e6-784ece1f9b0d.webm)
1. `/friend`를 통해 친구 목록 확인
2. 존재하지 않는 사용자 `sssss`에 대한 요청인 `/tag/sssss`을 통해 `404` 코드와 존재하지 않는 사용자라는 메시지가 반환됨을 확인
3. 친구가 아닌 사용자 `j0702`에 대한 요청인 `/tag/j0702`을 통해 `403` 코드와 친구가 아닌 사용자의 태그를 조회할 수 없다는 메시지가 반환됨을 확인
4. 친구인 사용자 `sy`에 대한 요청인 `/tag/sy`을 통해 태그의 …
> [BE] [4-26] 친구의 태그 조회 API 구현

- client/src/components/MainContainer/Log.tsx
- client/src/components/TaskModal/TagInput.tsx
- client/src/components/TaskModal/TaskModal.tsx
- 로그 컴포넌트와 상태를 최대한 분리했습니다.
- 43번 티켓이 해결되었습니다. (태스크모달 태그 색 변경 관련 버그 수정)
- 기존 코드에서 색 변경 시 부모 컴포넌트의 상태를 변경하던 것이 원인이었던 것 같습니다.
> [FE] [46] [43] 태스크 생성 모달 결합도 감축

- client/src/components/MainContainer/GoalManager.style.ts
- client/src/components/MainContainer/GoalManager.tsx
[9228aebc-47c4-465a-8742-42029f8b617e.webm](https://user-images.githubusercontent.com/55306894/205426038-827746d6-0ab3-426e-b259-46fec7f2b62a.webm)
> [FE] [56] 목표 탭 스타일링

- server/src/api/goal.ts
목표를 생성할 수 있는 API를 구현하였습니다.
- 요청 URL : `/goal`
- Request Body
- `{ title: string, date: string(yyyy-mm-dd), labelIdx: number, amount: number, over: boolean }`
- 모두 필수 값
- method : `POST`
- 응답
- 목표 생성 성공 : `201`
- 유효하지 않은 입력 : `400`
- 존재하지 않는 라벨 입력 : `404`
1. `/label`을 통해 라벨 목록 확인
2. `labelIdx`가 입력되지 않은 요청
3. `400` 코드가 반환되는 것을 확인
4. 존재하지 않는 `idx = 100` 라벨을 입력한 목표 생성 요청
5. `404` 코드가 반환되는 것을 확인
[d6421330-15ca-4fa7-830a-1dc469da4857.webm](https://user-images.githubusercontent.com/92143119/205644077-9a28abba-a5b3-4e1f-9995-8c2aba186cfa.webm)
1. `/goal?date=2022-12-05`를 통해 목표 목록 확인
2. 목표 생성 요청
3. `/goal?date=2022-12-05`를 통해 목표가 올바르게 생성된 것을 확인
[148c2d3b-2ec4-488a-873c-581b5e3db2ab.webm](https://user-images.githubusercontent.com/92143119/205644089-f155f3cb-1407-40bc-aa02-6e …
> [BE] [8-6] 목표 생성 API 구현

- client/src/components/MainContainer/GoalManager.style.ts
- client/src/components/MainContainer/GoalManager.tsx
- client/src/components/TaskModal/LabelInput.tsx
- client/src/components/common/Modal.tsx
- client/src/types/type.d.ts
- 목표를 생성할 수 있는 모달을 작성했습니다.
[94df2fa7-0c53-49c6-8d10-642652794a58.webm](https://user-images.githubusercontent.com/55306894/205672675-95f041c1-cd4d-4537-8504-582e8663b5cb.webm)
1. 재사용성을 고려해 `LabelList` 컴포넌트를 `LabelInput` 컴포넌트로부터 분리했습니다.
2. `LabelList`를 재사용해 목표 생성 모달을 작성했습니다.
3. 라벨 생성 모달을 작성했습니다.
- 목표 생성 API 연결 필요
> [FE] [8-14] 목표 생성 모달

- server/src/api/label.ts
- 잘못된 라벨 생성 요청을 보냈을 때 서버가 죽는 문제를 해결했습니다.
> [BE] [61] 라벨 생성 API 입력값 검증 추가

- server/package-lock.json
- server/package.json
redis 사용 위해 redis npm 설치했습니다
없다면 생략
1.Server: redis 설치
1.
-
> Update Dependencies: redis

- server/src/api/emoticon.ts
친구의 태스크 이모티콘 목록을 조회할 수 있도록 해당 API를 수정하였습니다.
- 요청 URL : `/emoticon/task/:task_idx`
- `task_idx` : 조회하고 싶은 태스크
- 응답
- `[ { idx, emoticon, author_name } ]` (이모티콘 객체 배열)
- 친구가 아닌 사용자에 대한 요청 : `403`
- 존재하지 않는 태스크에 대한 요청 : `404`
1. 친구가 아닌 사용자의 `idx = 1` 태스크에 대한 요청
2. `403` 코드와 친구가 아닌 사용자의 정보를 조회할 수 없다는 메시지가 반환되는 것을 확인
[f1e8822f-d7be-417d-bce3-56e7722ba651.webm](https://user-images.githubusercontent.com/92143119/205822576-1cbddc3b-a043-4f4e-aaf6-e6f85f77236e.webm)
1. `/task/sy?date=2022-12-01`을 통해 친구의 태스크 목록 확인
2. `/emoticon/task/89`를 통해 친구의 태스크 이모티콘 목록 조회 요청
3. 정상적으로 응답이 반환되는 것을 확인
[34d7e044-9a78-4fd3-bc60-d8e057cb4561.webm](https://user-images.githubusercontent.com/92143119/205822587-c17f9fd1-93fb-4744-8d30-86604727ecf4.webm)
1. 친구의 태스크 이모티콘 목록을 조회할 수 …
> [BE] [62] 태스크 이모티콘 목록 조회 API 수정

- client/src/components/MainContainer/GoalManager.style.ts
- client/src/components/MainContainer/GoalManager.tsx
목표 모달 내부에서 라벨 색상을 변경할 수 있습니다.
[7a6d0556-8d38-4fe2-a538-66a5b0a5a457.webm](https://user-images.githubusercontent.com/55306894/205880205-ef949eae-e6b8-4d5d-ba75-292984891dbb.webm)
> [FE] [68] 목표 모달 - 라벨 색상 변경 기능

- client/src/components/FriendsBar/FriendsBar.style.ts
- client/src/components/FriendsBar/FriendsBar.tsx
- client/src/components/MainContainer/Calendar.style.ts
- client/src/components/TopBar/TopBar.style.ts
친구 프로필사진에 마우스를 올리면 친구 ID가 나타납니다
1. hover::after css로 hover시 userId를 담은 pseudo element가 나타나도록함
1. 친구 프로필 사진 위로 마우스를 이동시켜 친구 아이디가 정확히 뜨는지 확인
-[4-12]
> [FE] [4-12] 친구 프로필사진 hover시 친구 ID가 나타나도록 구현

- client/src/components/MainContainer/GoalManager.tsx
- 서버 유효성 검증 테스트 목적으로 비웠던 body를 다시 돌려놓았습니다.
> [FE] [67] 목표 모달에서 잘못된 API 호출을 하고 있던 점 수정

- server/src/api/label.ts
라벨 수정 API를 작성했습니다
1. 로그인을 완료하세요
2. 개발자 도구를 열고 다음 코드를 입력하세요
```js
fetch(`http://localhost:8080/api/v1/label/${labelIdx}`, {
method: 'PATCH',
headers: {
},
title: 'zz',
color: '#aaffff',
}),
});
```
3. DB에 반영됐는지 확인하세요
1. body에 `color`가 포함된 케이스
- 자신의 다른 라벨의 `title`과 중복된 `title`을 body에 포함시킨 경우: `206`
- 그렇지 않은 경우: `200`
2. body에 `color`가 포함되지 않은 케이스
- 자신의 다른 라벨의 `title`과 중복된 `title`을 body에 포함시킨 경우: `409`
- 그렇지 않은 경우: `200`
> [BE] [8-17] 라벨 수정 API

- client/src/components/MainContainer/GoalManager.style.ts
> [FE] [66] 목표 생성 모달 스타일링

- client/src/components/MainContainer/GoalManager.tsx
함수명을 잘못 호출해 앱이 작동하지 않던 문제를 해결했습니다.
> [FE] [70] 잘못된 함수명을 사용하고 있던 문제 해결

- client/src/components/MainContainer/GoalManager.tsx
목표 탭에 조회 API를 연결했습니다. 이제 DB에서 얻어온 목표들을 렌더링합니다.
[399ff2ef-bf2f-4b41-acd5-01627d152d42.webm](https://user-images.githubusercontent.com/55306894/205846860-c45e1f36-8046-4c16-8df8-c44230ecd609.webm)
> [FE] [8-16] 목표 조회 API 연결

- client/src/components/TaskModal/TaskModal.tsx
- 이제 위치를 등록했다가 지우면 더이상 기존 위치가 요청에 남아 있지 않습니다.
> [FE] [40] 태스크 생성 모달 - 위치 삭제 시 body에 반영되도록 수정

- server/app.ts
- 이제 소켓 이벤트를 수신한 서버가 해당 이벤트 발신자 id를 알 수 있습니다.
[cb052534-e009-4c95-bfb6-fd0f264c2186.webm](https://user-images.githubusercontent.com/55306894/206127381-e9f56d63-cee7-41e5-b6ea-f2a051902bcb.webm)
- 클라이언트가 탭 이동으로 다이어리에 접근할 경우 소켓 이벤트를 두 번 보내는 이슈가 있는 것 같습니다.
> [BE] [6-11] 소켓 인증

- client/public/commentInput.svg
- client/src/components/MainContainer/Log.style.ts
- client/src/components/MainContainer/Log.tsx
- client/src/components/MainContainer/TaskItem.tsx
- client/src/types/type.d.ts
- 테스크의 이모티콘을 확인하고, Hover 시 이모티콘 남긴 사람을 확인할 수 있습니다.
- 친구의 테스크에 이모티콘을 남길 수 있습니다.
- 테스크를 클릭하면 상세정보와 더불어 이모티콘 목록이 표시됩니다. 같은 이모티콘을 두개 이상 받았을 시에는 숫자가 표시됩니다.
- 이모티콘을 Hover하면 남긴 사람이 표시됩니다.
- 친구의 테스크에 이모티콘을 남길 수 있습니다.
- 이모티콘을 남기면 본인이 남긴 이모티콘이 추가됩니다.
- TaskItem 내 이모티콘 리스트 , 이모티콘 인풋
- 친구의 task 조회 시 드래그앤드롭 불가능
7-34
7-12
- 일부 상황에 따라 남긴 사람 아이디가 짤려보일 수 있습니다. 추후 여유가 있을 때 수정을 고려하겠습니다.
> [FE] [7-34] 테스크 이모티콘 조회 / 보내기 기능

- client/src/components/MainContainer/GoalManager.tsx
- 이제 날짜에 맞는 목표 리스트가 표시됩니다.
[2cedc4fc-b4a9-4f30-943f-9b978ac9b171.webm](https://user-images.githubusercontent.com/55306894/206153099-5e1a3c94-5cf9-411c-97f4-08c690069ea7.webm)
> [FE] [74] 날짜가 바뀌어도 목표 리스트가 렌더링되지 않는 문제 해결

- client/src/components/MainContainer/GoalManager.tsx
- UI 로직으로 색상 변경을 할 수 없던 문제를 해결했습니다.
> [FE] [8-19] 목표 탭 - 라벨 색상 변경 API 주소가 잘못되어 있던 점 수정

- client/src/components/MainContainer/GoalManager.tsx
- 친구가 설정한 목표를 볼 수 있습니다.
[b5061a6a-0f79-4bf3-9da0-449979d45aeb.webm](https://user-images.githubusercontent.com/55306894/206374158-4d0e48f6-d934-4cb1-b075-c4408cddcaa4.webm)
> [FE] [4-29] 친구의 목표 조회

- client/src/components/FriendsBar/FriendsBar.style.ts
- client/src/components/FriendsBar/FriendsBar.tsx
- client/src/components/FriendsBar/FriendsBarAPI.ts
- client/src/components/MainContainer/Canvas.tsx
- client/src/constants/index.ts
- client/src/pages/MainPage.tsx
친구를 삭제할 수 있습니다.
1. 친구메뉴에서 삭제하기를 클릭하면 친구삭제 확인 모달이 나타납니다
2. cancle을 클릭하면 친구삭제가 취소됩니다.
3. accept를 누르면 친구가 삭제되며 친구목록이 리셋됩니다.
1. 친구창에서 삭제하고자하는 친구를 우클릭한다.
2. 메뉴에서 삭제하기를 클릭한다
3. 확인창에서 Accept를 클릭하고 정상적으로 삭제되었는지 확인한다.
-[4-14]
> [FE] [4-14] 친구삭제 기능 구현

- client/src/components/MainContainer/GoalManager.tsx
- 100% 이후에도 wave 요소 위치가 밀리는 현상을 고쳤습니다.
> [FE] [83] 목표 달성량 일정 이상 초과 시 Progress Bar가 제대로 표시되지 않던 문제 해결

- client/src/components/MainContainer/GoalManager.style.ts
- client/src/components/MainContainer/GoalManager.tsx
> [FE] [81] 목표 목록이 컨테이너를 뚫고 나오는 문제 해결

- server/src/api/calendar.ts
월 단위로 친구의 일별 태스크 존재 여부를 조회할 수 있는 API를 구현하였습니다.
- 요청 URL : `/calendar/task/:user_id?year=${year}&month=${month}`
- `user_id` : 조회하고 싶은 친구의 아이디
- `year` : 조회하고 싶은 연도
- `month` : 조회하고 싶은 달
- 응답
- `boolean[]` (존재 여부 배열)
- 배열의 크기는 요청한 달의 일수입니다.
- `배열의 0번 index = 1일의 정보`, ... , `배열의 30번 index = 31일의 정보`
- 본인에 대한 요청 : `/calendar/task?year=${year}&month=${month}`로 `redirect` 처리
- 연도 및 달 미지정, 잘못된 달 입력 : `400`
- 친구가 아닌 사용자에 대한 요청 : `403`
- 존재하지 않는 사용자에 대한 요청 : `404`
1. `/friend`를 통해 친구 목록 확인
2. 존재하지 않는 `kk` 사용자 에 대한 요청
3. `404` 코드와 함께 존재하지 않는 사용자라는 메시지가 반환되는 것을 확인
4. 친구가 아닌 `j0702` 사용자에 대한 요청
5. `403` 코드와 함께 친구가 아닌 사용자의 정보를 조회할 수 없다는 메시지가 반환되는 것을 확인
6. 친구인 `sy` 사용자에 대한 요청
7. 일별 태스크 존재 여부 배열이 반환되는 것을 확인
8. 자신의 아이디인 `pikachu` 에 대한 요청
9. …
> [BE] [4-32] 친구의 일별 태스크 존재 여부 조회 API 구현

- client/src/components/FriendsBar/FriendsBar.tsx
- client/src/components/MainContainer/Calendar.style.ts
- client/src/components/TopBar/Clock/Clock.style.ts
- client/src/components/TopBar/TopBar.style.ts
conflict 해결 과정에서 문제가 생겨 고치
없다면 생략
1. merge 오류 해결
2. z-index 수정
1.
-[88]
> [fix] [88] conflict resolve 에러 수정 및 친구메뉴/hover text 가림문제 해결

- server/src/api/calendar.ts
월 단위로 일별 평균 목표 달성률을 조회할 수 있는 API의 응답값이 실제 평균 목표 달성률과 일치하지 않는 문제가 있었습니다.
확인 결과 해당 날짜가 아닌 태스크도 포함해서 계산하여 발생한 문제였습니다.
목표와 날짜가 일치하는 태스크만 계산하도록 SQL을 수정하여 해결하였습니다.
기타 변경 사항은 없으며 아래 응답 및 요청, 작동 화면 및 테스트 방법은 아래 PR과 동일합니다.
- https://github.com/boostcampwm-2022/web19-Boostart/pull/168
1. 해당 날짜가 아닌 태스크의 라벨도 포함하여 목표 달성률을 계산하던 버그 수정
1. 로그인을 완료합니다.
9. 주소창에 `http://localhost:8000/api/v1/calendar/goal?year=${year}&month=${month}`를 입력합니다.
- [77]
UI 상에서 `0.1666625`의 평균 목표 달성률을 가지는 날짜, `0`의 평균 목표 달성률을 가지는 날짜, 목표가 없는 날짜를 구분할 수 없어서 범위에 따라 그라데이션 값을 지정해주는 등의 작업이 이루어지면 좋을 것 같습니다! 목표가 없는 날짜와 목표가 있으나 달성률이 0인 날짜 간의 구분이 필요하다면 말씀해 주세요! 목표가 없는 날짜의 값을 `-1`로 지정하는 등의 조치를 취하겠습니다.
> [BE] [77] 일별 평균 목표 달성률 조회 API 수정

- server/app.ts
> [BE] [90] 만료된 토큰을 가지고 서버 접근 시 서버가 죽는 문제 해결

- client/src/components/Drawer/Drawer.tsx
- client/src/components/common/dummy.ts
> [FE] [95] Drawer 알림 API 연결

- server/src/api/alarm.ts
- server/src/api/index.ts
> [BE] [96] 알림 API 작성

- server/app.ts
- server/src/core/socket.ts
- server/src/core/store.ts
- 세션 저장소 파일 분리
- 소켓 클래스화
- 알림을 실시간으로 표시하는 데 있어 필수적인 변경입니다.
> [BE] [94] 전역 저장소 및 소켓 파일 분리

- server/app.ts
- 소켓 세션을 정리하는 코드를 추가했습니다.
```
-- 연결중인 소켓 커넥션에 대한 유저 아이디 목록 --
{
hapYJREG_7vLQPySAAAA: 32,
FxiuWbSEHH6BQyE3AAAC: 8,
b_x11FlERn7HDzkzAAAE: 8,
'0kRnMPGpjKk_5g-KAAAG': 32,
Rn8o83hSt2FdU6VRAAAI: 32,
zYNNFgmgvVyvHec8AAAK: 32,
iUi3KJgXNHdFJRQwAAAM: 32
}
```
```
-- 연결중인 소켓 커넥션에 대한 유저 아이디 목록 --
{ 'SAsKl84ySpuY-1KYAAAE': 8, 'CrMp1maRHus-JNhOAAAI': 32 }
```
> [BE] [93] 불필요한 소켓 세션 삭제

- client/src/components/MainContainer/GoalManager.tsx
- 목표를 수정할 수 있습니다.
[f695b8c0-4283-4700-9405-3d5cf325750c.webm](https://user-images.githubusercontent.com/55306894/206840087-e90fd37b-4247-4777-99e6-7ab34500c9a2.webm)
- 목표 목록이 바로 업데이트되지 않는 현상은 https://github.com/boostcampwm-2022/web19-Boostart/pull/201 이 머지 후 해결됩니다.
> [FE] [8-9] 목표 수정 모달

- .gitignore
- server/app.ts
- server/src/constants/index.ts
HTTPS 설정을 완료하였습니다.
HTTP로 접속할 경우 HTTPS로 redirect 되도록 처리하였습니다.
**SSL 인증서와 환경 변수 설정은 Slack에 공유하였습니다.
SSL 인증서의 위치는 프로젝트의 루트 폴더입니다.**
1. HTTPS 설정
2. HTTP로 접속 시 HTTPS로 redirect 처리
- [55]
> [BE] [55] HTTPS 설정

- client/package.json
- server/app.ts
- server/src/constants/index.ts
- 다시 devServer의 hot reload를 이용할 수 있습니다.
- ### 환경변수 파일 내용은 팀 Slack을 참고해주세요
1. devServer 실행 방법 (터미널 2개)
```
cd server
npm run dev
```
```
cd client
npm run dev
```
2. 빌드 결과 실행 방법 (https)
```
cd client
npm run build
cd ../server
npm run start
```
> [106] 다시 devServer에서 개발할 수 있도록 환경변수 관련 수정

- client/src/components/TaskModal/TaskModal.tsx
- 태스크 생성 시 공개 여부 기본값이 true로 설정됩니다.
- 태스크 수정 시 공개 여부 기본값이 기존 공개 여부로 설정됩니다.
> [FE] [104] 태스크 공개 여부 기본값 설정
