boostcampwm-2022/web19-Boostart

server/src/api/task.ts
`executeSql` 의 두 번째 매개변수 타입인 `string[]`에 맞게 캐스팅
=> [티켓추가예정] number 타입을 prepare statement에 넣기 위해 string으로 캐스팅

server/src/api/index.ts, server/src/api/tag.ts
태그를 DB에서 불러오는 API와 DB에 추가하는 API를 작성했습니다.
1. 태그 생성 API 작성
2. 태그 조회 API 작성
1. 로그인을 완료하세요.
3. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/tag', {
headers: {
},
body: JSON.stringify({title: '태그', color: 'ffffff'}),
});
```
4. 주소창에 `http://localhost:8000/api/v1/tag`를 입력하세요.
=> [BE] 태그 생성 및 조회 API

server/src/api/tag.ts
- 태그 생성 시 생성된 요소에 대한 idx 값 반환
- **task 생성 모달에서 task 생성을 위해 tag_idx를 post 해야하기 때문**에 필요하다고 판단됨
- `/api/v1/tag` response 에 생성된 tag에 대한 idx 추가
- 테스트 방법
```
fetch('http://localhost:8000/api/v1/tag', {
headers: {
},
body: JSON.stringify({title: '태그', color: 'ffffff'}),
});
```
=> [BE]  태그 생성 API - 반환 값에 idx 추가

client/src/components/MainPage/MainContents/Log/TaskItem.tsx, client/src/components/MainPage/MainContents/Log/index.tsx, client/src/components/MainPage/MainContents/Log/style.ts, client/src/types/type.d.ts
체크박스 기반으로 하여 완료/미완료를 선택가능하며 선택한 옵션의 task만 볼 수 있습니다.
1. 완료/미완료 체크박스 버튼을 만들었습니다.
2. 완료/미완료 체크박스 상태를 useState로 관리합니다.
3. 완료/미완료 체크박스 상태와, task의 완료 여부를 나타내는 done 값에 따라 각 task의 render 여부를 결정합니다.
4. 라디오박스 추가에 따라 일부 기존 element에 CSS 수정이 있습니다.
- 7-19
=> [FE] [7-19] 태스크 완료/미완료 filter 기능 구현

server/src/api/task.ts
API 문서에 명시된 대로 body에 필요한 필드를 추가했습니다.
1. `task` 테이블에 추가적으로 `날짜`, `시작 시각`, `종료 시각`, `좌표`, `완료 여부`, `태그`, `내용` 컬럼이 입력되도록 수정했습니다.
2. `task_label` 테이블에 행을 삽입하는 과정이 추가되었습니다.
3. 
1. 로그인을 완료하세요.
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/task', {
headers: {
},
title: '낮잠',
importance: 5,
startedAt: '11:00',
endedAt: '22:00',
lat: 37.3584879,
lng: 127.105037,
isPublic: true,
tagIdx: 1,
content: 'zzZ..',
done: false,
date: '2022-11-22',
labels: [
{
labelIdx: 1,
amount: 11
}
]
}),
});
```
3. 주소창에 `http://localhost:8000/api/v1/task`를 입력하세요.
=> [BE] task 생성 API 보완

client/src/components/MainPage/MainContents/Log/TaskItem.tsx, client/src/components/MainPage/TaskModal/TagInput.tsx, client/src/components/MainPage/TaskModal/index.tsx, client/src/components/MainPage/TaskModal/style.ts, client/src/types/type.d.ts
- 태스크 생성 모달 내의 태그 Input 창
- 태그 Input 바를 클릭 시 태그 리스트가 띄워짐
- 해당 리스트는 스크롤로 확인
- 요소 hover 시 background color 변경
- 요소 클릭 시 해당 요소가 선택됨 
- 선택된 요소의 x 버튼 클릭 시 선택이 해제되고 초기 상태로 돌아옴
- 키보드 입력 시 입력 값의 검색 결과 리스트가 띄워짐
- 결과 외에도 마지막 열의 '생성 : ' 요소를 클릭하면 새로운 요소를 추가할 수 있음 (새로운 tag post)
- 새로운 요소 추가시 해당 요소가 랜덤 색상과 함께 선택됨 
- 선택 요소 해제 후 확인되는 리스트에서 태그가 생성되었음을 확인할 수 있음
- 태그 Input 바 클릭 시 리스트 띄워짐
- 태그 Input 바를 제외한 위치를 클릭 시 리스트 사라짐
- TagInput 컴포넌트 추가
- TaskModal 에서 TagInput 컴포넌트 사용
- TagInput 컴포넌트에서 `태그 선택` 시 TaskModal의 `tagIdx`값에 해당 태그의 idx 저장 ( 현재 test를 위해 해당 값 콘솔에 찍힘 ) 
- #54 
- 이름이 동일한 태그 생성 가능 여부 논의 중에 있습니다.
- tag 생성 실패 예외처리 추후 추가
- onMouseDown -> onBlur -> onClick 순으로 이벤트가 일어나기 때문에 onMouseDown을 이용했습니다.
- API 연결 완료된 상태입니다.
- axios.defaults.withCredentials = true; 전역 설정으로 CORS 해결했습니다.
- #56 의 내용이 반영되어야 정상 작동합니다.
=> [FE] [7-16] 태스크 생성 모달 내 태그 조회 / 생성 / 선택 Input 창

server/src/api/auth.ts, server/src/api/tag.ts, server/src/api/task.ts, server/src/db/index.ts
쿼리 실행을 추상화한 함수 `executeSql`에서 error를 catch하는 동작을 제거했습니다.
[cf6110ac-852e-414b-8570-760982986924.webm](https://user-images.githubusercontent.com/55306894/203225804-4d63e174-ab7f-457c-aed8-2c01de7f3c73.webm)
=> [BE] [7-17] 비정상적인 요청 시 에러 코드 응답을 위해 쿼리 실행 함수에서 try-catch 제거

client/src/components/TaskModal/TaskModal.style.ts, client/src/components/TaskModal/TaskModal.tsx
- task 생성 모달의 더보기 버튼 활성화
- 더보기 버튼을 누르면 추가 정보 입력 폼이 표시된다.
- 닫기 버튼을 누르면 초기 상태로 돌아온다.
1. isDetailOpen 상태값을 통해 더보기 버튼 활성화
2. 메모 입력 란에 다중 줄 text 입력 바 추가
위치 / 라벨은 추가 pr로 올릴 예정입니다.
=> [FE] [7-15] task 생성 모달 더보기 기능 추가

server/src/api/tag.ts
자신의 태그를 삭제하는 API를 작성했습니다.
[9a738151-d93e-4b36-ba52-7c3561bdbb9b.webm](https://user-images.githubusercontent.com/55306894/203259687-19be5bdc-981b-4b9d-84a4-dc21554766d0.webm)
1. `http://localhost:8000/api/v1/tag`에 접속하면 자신의 태그를 확인할 수 있습니다.
2. 자신의 태그 중 삭제하길 원하는 태그의 인덱스 `n`에 대해 콘솔에 다음 명령어를 입력하세요.
```
fetch(`http://localhost:8000/api/v1/tag/${n}`, {
method: 'delete',
headers: {
}
});
```
3. 페이지를 새로고침하세요.
=> [BE] [7-17] tag 삭제 API

.gitignore, client/src/components/SignupMenu/SignupMenu.tsx, server/src/api/auth.ts, server/src/types/index.d.ts
- 회원가입 페이지에서 업로드한 파일이 서버 컴퓨터에 파일 형태로 저장됩니다.
[c01262e8-2418-4c99-a9e6-0a984491e038.webm](https://user-images.githubusercontent.com/55306894/203258581-c7b427fd-03f7-445c-927f-1554bdb2576c.webm)
1. API 수정
2. 클라이언트에서 회원가입 요청을 보내는 코드 수정
1. 로컬 환경에서 테스트해주세요.
2. 회원가입 시 프로필 사진을 업로드하세요.
3. 나머지 필드를 채우고 회원가입을 완료해주세요.
4. `server/upload/`에 업로드한 이미지 파일이 생겼는지 확인하세요.
=> [FE/BE] [2-4] 프로필 사진 업로드 기능

server/src/api/index.ts, server/src/api/user.ts
친구 추가 시 유저의 아이디를 통해 유저를 검색할 수 있도록 하기 위한 API를 구현하였습니다.
검색 키워드를 포함하는 id를 모두 결과에 포함시켰습니다.
만약 `abc`라는 id를 가진 유저가 존재하고 `bc`라는 키워드를 통해 유저를 검색하였다면 `abc` 유저 또한 검색 결과에 포함됩니다.
1. user route 설정
2. 유저 검색 API 구현
1. 로그인을 완료합니다.
2. 주소창에 `http://localhost:8000/api/v1/user?user_id={검색하고 싶은 id}`을 입력합니다.
- 4-9
=> [BE] [4-9] 친구 추가를 위한 유저 검색 API 구현

server/src/api/friend.ts, server/src/api/index.ts, server/src/api/user.ts
친구 목록을 조회할 수 있는 API를 구현하였습니다.
~~해당 API를 통해 친구 목록과 친구 요청 목록을 모두 조회할 수 있게 하기 위해 `accepted`를 입력 받아 `accepted=true`이면 친구 목록을, `accepted=false`이면 친구 요청 목록을 조회할 수 있게 하였습니다.~~
친구 목록과 친구 요청 목록을 조회하는 API를 분리하기로 하여 위 내용은 삭제합니다.
1. friend route 설정
2. 친구 목록 조회 API 구현
1. 로그인을 완료합니다.
2. 주소창에 `http://localhost:8000/api/v1/friend`를 입력합니다.
- 4-10
branch 생성을 4-9 branch에서 해버려서 4-9 내용이 이 PR에 포함되어 버렸습니다..!
`friend.ts` 부분만 봐주시면 될 것 같습니다
=> [BE] [4-10] 친구 목록 조회 API 구현

server/src/api/tag.ts
태그의 컬러를 수정하는 API 입니다.
1. 로그인 후 다음 명령어로 작동 확인할 수 있습니다.
```
fetch('http://localhost:8000/api/v1/tag/color/${tag_idx}', {
headers: {
},
body: JSON.stringify({ color: '#dddfff'}),
});
```
- API 문서에 추가했습니다.
- CORS 오류로 인해 POST 방식으로 진행했습니다.
- 에러코드 분류에 대한 기준을 공유해주셨으면 좋겠습니다.
=> [BE] [7-17] 태그 컬러 수정 API 추가

server/src/api/friend.ts
사용자에게 온 친구 요청의 목록을 조회하는 API를 구현하였습니다.
결과값 : `[{idx, user_id, username, profile_img}]` (친구 요청을 보낸 사용자 객체 배열)
1. 로그인을 완료합니다.
2. 주소창에 `http://localhost:8000/api/v1/friend/request`를 입력합니다.
- 4-15
기존 API 문서에서 해당 API 요청 URL이 `/friend/req`였는데 줄임말을 사용하는 것의 이점이 없는 같아 `friend/request`로 변경하였습니다. API 문서 함께 참고 부탁드립니다.
=> [BE] [4-15] 친구 요청 목록 조회 API 구현

server/src/api/friend.ts
친구를 삭제하는 API를 구현하였습니다.
- 요청 URL : `/friend/:user_idx`
- `user_idx` : 삭제하고 싶은 친구의 idx
- 응답
- 삭제 성공 : `200`
- 해당 친구가 존재하지 않아 삭제 불가 : `404`
1. `/friend`를 통해 친구 목록 확인
2. 개발자 도구 콘솔에 아래의 명령어 입력 후 실행
```js
fetch('http://localhost:8000/api/v1/friend/12', {
method: 'delete',
headers: {
}
});
```
3. `/friend`를 통해 친구 목록을 확인하여 삭제가 완료되었음을 확인
[8290ffe6-d94b-42bb-a1f6-32a3d82e5edf.webm](https://user-images.githubusercontent.com/92143119/203488607-089bae59-188c-4a25-a335-a241d077e5c3.webm)
1. 친구 삭제 API 구현
1. 로그인을 완료합니다.
```js
fetch('http://localhost:8000/api/v1/friend/${user_idx}', {
method: 'delete',
headers: {
}
});
```
- 4-13
=> [BE] [4-13] 친구 삭제 API 구현

server/src/api/friend.ts
친구 요청을 전송하는 API를 구현하였습니다.
- 요청 URL : `/friend/request/:user_idx`
- `user_idx` : 친구 요청을 보내고 싶은 사용자
- 응답
- 친구 요청 성공 : `201`
- 이미 나에게 친구 요청을 보냈던 사용자에게 친구 요청을 보낼 경우 자동으로 친구가 됨 : `200`
- 친구 요청을 이미 보냈거나 이미 친구인 경우 : `409`
- 존재하지 않는 사용자에 대한 친구 요청 : `404`
- 스스로에 대한 친구 요청 : `409`
1. 친구 요청 전송 API 구현
현재 친구 관계에 대한 테이블 `friendship`의 정보는 아래와 같습니다.
- `sender_idx` = 친구 요청 전송자
- `receiver_idx` = 친구 요청 수신자
- `accepted` = 친구 요청 승인 여부 (true이면 친구 관계, false이면 친구 요청 대기 상태)
<br>
```
+--------------+------------+------+-----+---------+-------+
| Field        | Type       | Null | Key | Default | Extra |
+--------------+------------+------+-----+---------+-------+
| sender_idx   | int(11)    | YES  | MUL | NULL    |       |
| receiver_idx | int(11)    | YES  | MUL | NULL    |       |
| …
```
=> [BE] [4-16] 친구 요청 API 구현

server/src/api/emoticon.ts, server/src/api/index.ts
다른 사용자가 나의 태스크에 남긴 이모티콘의 목록을 조회할 수 있는 API를 구현하였습니다.
- 요청 URL : `/emoticon/task/:task_idx`
- `task_idx` : 조회하고 싶은 태스크
- 응답
- `[{idx, emoticon, author_name}]` (이모티콘 정보 객체 배열)
- 존재하지 않는 태스크에 대한 실행 : `404`
1. `/task`를 통해 현재 태스크의 목록을 조회
2. `/emoticon/task/10`를 통해 현재 존재하지 않는 `idx = 10` 태스크에 대한 이모티콘 목록 조회 요청
3. 존재하지 않는 태스크라는 메시지가 반환됨을 확인
[fff7cdc4-1069-4d40-9f0d-07a109a5a476.webm](https://user-images.githubusercontent.com/92143119/204086810-15971251-7f23-4ff1-add2-59649af09070.webm)
1. `/task`를 통해 현재 태스크의 목록을 조회
2. `/emoticon/task/14`를 통해 현재 존재하는 `idx = 14` 태스크에 대한 이모티콘 목록 조회 요청
3. 정상적으로 이모티콘 목록이 반환됨을 확인
[896dcc3b-2ff9-41da-b9c9-7adbbf5fb0a1.webm](https://user-images.githubusercontent.com/92143119/204086883-321ef39a-c64c-49ba-a370-a85c68f579aa.webm)
1. …
=> [BE] [7-26] 태스크 이모티콘 조회 API 구현

server/src/api/task.ts
task 조회 API 호출 시 URL query string에 date를 포함시켜야 동작하도록 수정하였습니다.
1. 로그인을 완료하세요.
2. 주소창에 `http://localhost:8000/api/v1/task?date=2022-11-22`을 입력하세요.
=> [BE] [15] task 날짜별로 조회하도록 수정

server/src/api/label.ts
라벨 조회 시 count(라벨 사용 횟수)를 함께 반환하도록 API를 수정하였습니다.
- 요청 URL : `/label`
- 응답
- `[{ idx, title, color, unit, count }]` (라벨 객체 배열)
1. `/label`을 통해 라벨의 목록이 반환됨을 확인
[328eca62-41ad-4dac-8e08-cb9de5a64342.webm](https://user-images.githubusercontent.com/92143119/204204135-14f7bf93-86e7-4507-9fa6-fee12c13c89c.webm)
1. 라벨 조회 시 count(라벨 사용 횟수)를 반환하도록 수정
2. `try catch` 문을 사용하여 서버에서 에러 발생시 `500` 코드를 반환하도록 수정
1. 로그인을 완료합니다.
2. 주소창에 `http://localhost:8000/api/v1/label`를 입력합니다.
- [24]
=> [BE] [24] 라벨 조회 API 수정

server/src/api/emoticon.ts, server/src/api/friend.ts, server/src/api/label.ts, server/src/api/tag.ts, server/src/api/task.ts, server/src/api/user.ts, server/src/db/index.ts
- `executeSql` 함수의 `values` 타입을 `string[]`에서 `any[]`로 변경하였습니다.
- SQL 문의 조건 등에 들어갈 값을 `values`에 배열의 형태로 전송하여 SQL 문을 실행하였는데
SQL 문의 특성 상 `values` 배열에는 `number`, `string` 등 다양한 타입의 값이 들어갈 수 있습니다.
- 따라서 타입을 지정하기 애매한 탓에 기존에는 `values`의 타입을 `string[]`으로 지정한 뒤
`values`에 담을 값을 `string`으로 변경해주는 작업을 수행하였으나
이는 불필요한 작업으로 여겨지며 `values` 배열에는 여러 타입의 값이 담기는 것이 정상적인 동작이므로
`values`의 타입을 `any[]`로 변경하기로 결정하였습니다.
- `values`에 담을 값을 `string`으로 변경하는 코드를 삭제하였습니다.
1. `executeSql`의 `values` 타입 변경
2. `executeSql` 사용 시 `values`에 담을 값을 `string`으로 변경하는 코드 삭제
3. `idx` 값 비교 시 숫자의 형태로 비교하도록 수정
- [26]
=> [BE] [26] executeSql 함수의 values 타입 변경

server/src/api/task.ts
task 생성 요청의 body에 일부 요소가 누락되어 있는 경우 해당 요소가 필수가 아님에도 서버가 죽는 에러를 수정하였습니다.
1. 로그인을 완료하세요.
2. 개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/task', {
headers: {
},
title: '낮잠',
date: '2022-11-22',
}),
}).then((res) => {
if (res.ok) console.log('GOOD');
});
```
3. 콘솔에 `GOOD`이 출력되는지 확인하세요.
=> [BE] [18] task 생성 요청 시 body에 필수 요소만 넣어도 동작하도록 수정

server/src/api/emoticon.ts, server/src/api/friend.ts, server/src/api/user.ts
API Response의 key 값을 camelCase 형태로 수정하였습니다.
- 변경된 Response key
- 태스크 이모티콘 조회 API
- `author_name` → `authorName`
- 친구 목록 조회 API, 친구 요청 목록 조회 API, 사용자 검색 API, 내 정보 조회 API
- `user_id` → `userId`
- `profile_img` → `profileImg`
1. API Response의 key 값 camelCase 형태로 수정
- [26]
**앞으로 API 작업 시 `user_id` 등 snake_case 형태의 컬럼 값이 응답에 포함될 경우에는 `select user_id as userId from user`와 같은 형태로 SQL 문을 작성하셔서 Response에 camelCase 형태의 key 값이 포함되도록 작업해주시면 될 것 같습니다.**
=> [BE] [26] API Response의 key 값을 camelCase 형태로 수정

server/src/api/tag.ts
태그를 삭제하기 전에 태그 존재 여부, 사용 여부를 검사하고 태그가 사용되지 않은 경우에만 태그를 삭제하도록 수정하였습니다.
- 요청 URL : `/tag/:tag_idx`
- `tag_idx` : 삭제하고 싶은 태그
- 응답
- 태그 삭제 성공 : `200`
- 존재하지 않는 태그 : `404`
- 사용 중인 태그에 대한 요청 : `409`
1. `/task?date=2022-12-01`을 통해 `idx = 3039` 태그가 사용 중임을 확인
2. 사용 중인 `idx = 3039` 태그에 대한 삭제 요청
3. `409` 코드가 반환됨을 확인
[fdab53ea-1463-4cc6-8392-c9df1798f288.webm](https://user-images.githubusercontent.com/92143119/204436295-8486de1a-d261-4971-827b-5b298bc4db66.webm)
1. `/tag`를 통해 태그 목록 확인
2. 존재하지 않는 `idx = 30424` 태그에 대한 삭제 요청
3. `404` 코드가 반환됨을 확인
4. 사용 중이지 않은 `idx = 3042` 태그에 대한 삭제 요청
5. `/tag`를 통해 태그가 정상적으로 삭제된 것을 확인
[f9bb03fc-476b-4959-9d22-e69080ce78d4.webm](https://user-images.githubusercontent.com/92143119/204339879-b4c6c681-0061-4578-92b0-3e0644830731.web …
=> [BE] [25] 태그 삭제 API 수정

server/src/api/label.ts
라벨을 삭제하는 API를 구현하였습니다.
- 요청 URL : `/label/:label_idx`
- `label_idx` : 삭제하고 싶은 라벨
- 응답
- 라벨 삭제 성공 : `200`
- 존재하지 않는 라벨 : `404`
- 사용 중인 라벨에 대한 요청 : `409`
1. 사용 중인 `idx = 11` 라벨에 대한 삭제 요청
3. `409` 코드가 반환됨을 확인
[fe9646ea-e4ce-4960-ac2f-e2c8f7572df5.webm](https://user-images.githubusercontent.com/92143119/204444956-907c52ce-7519-4eb6-8777-caebb6031de2.webm)
1. `/label`를 통해 라벨 목록 확인
2. 존재하지 않는 `idx = 15` 라벨에 대한 삭제 요청
3. `404` 코드가 반환됨을 확인
4. 사용 중이지 않은 `idx = 10` 라벨에 대한 삭제 요청
5. `/label`를 통해 라벨이 정상적으로 삭제된 것을 확인
[88dae6ca-a841-43fb-8928-c3325f3a50fd.webm](https://user-images.githubusercontent.com/92143119/204445065-cc33232e-857a-4025-aa00-54971afd8ffc.webm)
1. 라벨 삭제 API 구현
1. 로그인을 완료합니다.
```js …
```
=> [BE] [7-28] 라벨 삭제 API 구현

server/src/api/label.ts
라벨을 추가하는 API에서 idx 값을 반환하도록 수정했습니다.
로그인을 완료하세요.
개발자 도구를 열고 다음 코드를 입력하세요.
```
fetch('http://localhost:8000/api/v1/label', {
headers: {
},
body: JSON.stringify({title: '잠자기', color: '#776677', unit: '시간'}),
});
```
주소창에 http://localhost:8000/api/v1/label을 입력하세요.
- 7-22
- 라벨을 생성 후 해당 라벨에 대한 task의 라벨 데이터를 등록해야 되기 때문에 필요
=> [BE] [7-22] 라벨 생성시 idx를 반환하도록 수정

server/src/api/task.ts
`executeSql` 함수의 매개변수 타입스크립트 제약이 제거됨에 따라 불필요한 타입 캐스팅을 제거했습니다.
=> [BE] [30] task 수정 API - 불필요한 타입 캐스팅 제거

client/src/components/MainContainer/Log.tsx, server/src/api/task.ts
`snake_case`를 `camelCase`로 변경했습니다
- `started_at` → `startedAt`
- `ended_at` → `endedAt`
- `tag_idx` → `tagIdx`
예약어를 API 필드 이름으로 사용하지 않도록 변경했습니다.
- `public` → `isPublic`
=> [FE/BE] [29] API 필드 이름 통일

client/src/components/FriendsBar/FriendSearchForm.tsx, client/src/pages/MainPage.tsx
친구 검색기능 통해 친구추가 요청 구현
1.MainPage에서 친구추가 API 요청 로직을 제공합니다.
2.친구추가 컴포넌트에서 해당 로직을 받아 친구를 선택하여 친구요청을 서버로 보냅니다.
3.현재 상황(친구요청완료, 친구 기요청여부)을 response로받아 alert 메세지를 띄웁니다.
1.로그인을하여 친구Bar에 있는 + 버튼을 누른다.
2.사용자를 검색한다.
3.친구로 추가하고자하는 사용자를 클릭하여 활성화된 request버튼을 누른다.
-[4-21]
=> [FE] [4-21] 검색창 통해 친구요청(API포함) 구현

server/src/api/task.ts
태스크 조회 시 라벨의 목록을 함께 반환하도록 API를 수정하였습니다.
- 요청 URL : `/task?date=${date}`
- `date` : 태스크를 조회하고 싶은 날짜
- 응답
- `[ { idx, title, importance, startedAt, endedAt, lat, lng, location, isPublic, tagIdx, tagName, content, done, labels: [ { labelIdx, title, color, unit, amount } ] } ]` (태스크 객체 배열)
- 날짜 미지정 : `400`
1. `/task`을 통해 날짜 미지정 시 `400` 코드와 날짜를 지정하라는 메시지가 반환됨을 확인
2. `/task?date=2022-12-01`을 통해 태스크 목록 조회 시 라벨의 목록이 함께 조회됨을 확인
3. `/task?date=2022-11-29`을 통해 라벨이 설정되지 않은 태스크 조회 시 라벨의 목록이 빈 배열로 조회됨을 확인
[c0ff9136-79c5-4d43-9269-3a9fd2884985.webm](https://user-images.githubusercontent.com/92143119/204459351-72384c34-c901-41ef-b18f-9747cb7d8754.webm)
1. 태스크 조회 시 라벨 목록이 조회되도록 태스크 조회 API 수정
2. `try catch` 문을 통해 에러 처리
1. 로그인을 완료합니다.
2. 주소창에 …
=> [BE] [23] 태스크 조회 API 수정

server/src/api/label.ts
라벨 생성 시 이미 존재하는 title을 사용하면 서버 에러가 발생하던 현상을 수정하였습니다.
DB label 테이블에 `(user_idx, title)` 의 unique 조건이 존재하는데 DB 요청 전 이를 미리 검사하지 않아 발생한 현상이었습니다.
DB 요청 전 해당 사용자에게 이미 동일한 title의 라벨이 존재하는지 검사한 후 존재한다면 `409` 코드를 반환하는 코드를 추가하였습니다.
- 요청 URL : `/label`
- `Request Body` : `{ title, color, unit }` (라벨 정보 객체)
- method : `POST`
- 응답
- `{ idx }` (생성된 라벨의 인덱스) : `201`
- 이미 존재하는 라벨 : `409`
1. 이미 존재하는 `수면` 라벨 생성 요청
2. `409` 코드가 반환되는 것을 확인
[6d68f345-a1e6-4f42-b7ed-e59a85506969.webm](https://user-images.githubusercontent.com/92143119/204477752-18752681-67d1-4c8c-9755-3a153cf94367.webm)
1. 이미 존재하는 title의 라벨 생성 요청 시 `409` 코드를 반환하도록 라벨 생성 API 수정
2. 라벨 생성 성공 시 `201` 코드를 반환하도록 수정
3. `try catch`를 통한 에러 처리
1. 로그인을 완료합니다.
```js …
```
=> [BE] [31] 라벨 생성 API 수정

client/src/components/Drawer/Drawer.style.ts, client/src/components/Drawer/Drawer.tsx, client/src/components/FriendsBar/FriendSearchForm.tsx, client/src/components/common/dummy.ts, client/src/constants/index.ts, client/src/pages/MainPage.tsx, client/src/types/type.d.ts
자신에게 온 친구 요청을 확인하고 수락하거나 거절할 수 있습니다.
첫번째는 거절/ 두번째 수락(친구목록 리셋)
1.친구요청목록 수신 API를 이용하여 친구요청 목록을 불러와 렌더링합니다.
2. 각 친구요청 목록에 있는 수락/거절 버튼을 누르면 친구요청을 수락하거나 거절할 수 있습니다.
1. 서로 친구가 아닌 계정이 2개 필요합니다.
2. 한 계정에서 다른 계정으로 친구 요청을 보냅니다.
3. 친구 요청을 보낸 계정으로 접속하여 친구요청을 확인합니다.
4. 거절하거나 수락하여 기능을 확인합니다.
-[4-19]
=> [FE] [4-19] 친구 요청 수락/거절 기능 구현

server/src/api/task.ts
친구의 태스크를 조회할 수 있는 API를 구현하였습니다.
친구인 사용자에 한해서만 태스크를 조회할 수 있으며 친구인 경우에도 공개(`public = true`)인 태스크만 조회할 수 있도록 하였습니다.
- 요청 URL : `/task/:user_id?date=${date}`
- `user_id` : 조회하고 싶은 친구의 id
- `date` : 태스크를 조회하고 싶은 날짜
- 응답
- `[ { idx, title, importance, startedAt, endedAt, lat, lng, location, isPublic, tagIdx, tagName, content, done, labels: [ { labelIdx, title, color, unit, amount } ] } ]` (태스크 객체 배열)
- 자신에 대한 요청 : `/task?date=${date}`로 redirect 처리하여 자신의 태스크를 조회하는 API 요청
- 날짜 미지정 : `400`
- 친구가 아닌 사용자에 대한 요청 : `403`
- 존재하지 않는 사용자에 대한 요청 : `404`
1. `/task/ss`을 통해 날짜 미지정 시 `400` 코드와 날짜를 지정하라는 메시지가 반환됨을 확인
2. 존재하지 않는 사용자 `ss`에 대한 요청인 `/task/ss?date=2022-12-01`을 통해 `404` 코드와 존재하지 않는 사용자라는 메시지가 반환됨을 확인 …
=> [BE] [4-25] 친구의 태스크 조회 API 구현

client/src/components/FriendsBar/FriendsBar.style.ts, client/src/components/FriendsBar/FriendsBar.tsx, client/src/components/MainContainer/Calendar.style.ts, client/src/components/MainContainer/Diary.style.ts, client/src/components/MainContainer/Diary.tsx, client/src/components/MainContainer/Log.style.ts, client/src/components/MainContainer/Log.tsx, client/src/components/MainContainer/MainContainer.style.ts, client/src/components/MainContainer/MainContainer.tsx, client/src/components/TaskModal/LabelInput.tsx, client/src/components/TaskModal/TaskModal.style.ts, client/src/components/TopBar/Clock/Clock.style.ts, client/src/components/TopBar/Clock/Clock.tsx, client/src/components/TopBar/TopBar.style.ts, client/src/components/TopBar/TopBar.tsx, client/src/components/common/GlobalStyle.ts, client/src/index.css, client/src/pages/MainPage.tsx
- 전반적인 css 조정
1. 창 크기를 줄였을 때 화면이 잘리고 MainContents의 위치가 올바르지 않은 이슈 수정
2. TopBar의 space-between 속성이 각 요소의 width가 다름에 따라 한쪽에 치우치는 문제 수정
3. 불필요한 스크롤이 생기는 문제 수정
4. Log 컴포넌트 내 TimeBar UI 조정
5. #110 에서 추가한 스크롤 디자인 조정
6. 상위 내용을 포함하여 전체적인 css 크기 및 디자인 조정
- 22 창 크기가 줄어들었을 때 화면이 짤리는 이슈
- 36 스크롤바 스타일링
- LOG, DIARY 타이틀이 해당 컴포넌트보다 뒤에 표시되는 이슈가 있습니다...
- LOG 컴포넌트 디자인은 LOG 추가 구현 진행하면서 따로 올리겠습니다!
=> [FE] [22] 화면이 짤리는 이슈 등을 포함한 화면 전반의 css 조정

server/src/api/task.ts
태스크를 수정할 수 있는 API를 구현하였습니다.
태스크의 `date`, `done`은 수정이 불가능합니다.
해당 API를 통해 `date`, `done`에 대해 수정 요청을 하더라도 수정되지 않고 기존의 값이 유지됩니다.
`done`의 경우 태스크 일부 수정 API(`PATCH`) 요청을 통해 수정할 수 있습니다.
수정하고 싶지 않은 값을 `null`로 설정하게 되면 해당 값이 `null`로 수정됩니다.
`labels` 입력은 다음과 같이 처리됩니다.
- `labels` 입력하지 않음 : `labels` 수정하지 않음
- `labels: undefined`로 입력 : `labels` 수정하지 않음
- `labels: []`로 입력 : 모든 `labels` 삭제
- `labels: [{ 새로운 라벨 정보 }]` : 새로운 라벨 정보로 갱신됨
- 내부에서는 새로운 라벨 정보와 기존의 라벨 정보를 비교하여 아래와 같은 동작을 수행합니다.
- 기존에 존재하던 라벨 정보 → 값이 바뀌었다면 수정, 아니면 두기
- 기존에 존재하던 라벨 정보가 새로운 라벨 정보에 없음 → 기존 라벨 정보 삭제
- 새로운 라벨이 추가됨 → 라벨 정보 추가
위의 사항을 참고하셔서 API 사용해주시면 될 것 같습니다.
- 요청 URL : `/task/:task_idx`
- `Request Body` : `{ title, importance, date, startedAt, endedAt, lat, lng, location, isPublic, tagIdx, content, done, labels: [ { labelIdx,  amount } ] …
=> [BE] [7-10] 태스크 수정 API 구현

client/src/components/MainContainer/GoalManager.style.ts, client/src/components/MainContainer/GoalManager.tsx, client/src/components/MainContainer/MainContainer.tsx, client/src/components/MainContainer/SubContainer.style.ts, client/src/components/MainContainer/SubContainer.tsx, client/src/constants/index.ts
목표 탭을 추가했습니다.
1. 공통 레이아웃에 쓸 `SubContainer` 컴포넌트 작성
2. 목표 탭에 맞게 이름을 수정했습니다.
- `PLAN` → `GOAL`
3. `GoalManager` 컴포넌트 작성
- 더미 데이터를 가지고 만들었으며, 더미 데이터는 6가지 필드로 이루어져 있습니다.
- `idx`, `title`,  `labelIdx`, `goalAmount`, `currentAmount`, `over`
- `labelIdx`를 통해 라벨 이름이나 단위를 알아내야 하므로 클라이언트는 label 목록을 미리 알고 있어야 합니다.
- 목표 세부 달성률은 클라이언트 단에서 계산합니다.
1. 로그인을 완료하세요.
2. GOAL 탭을 누르세요.
=> [FE] [8-1] 목표 탭 기본 레이아웃 작업

client/src/App.tsx, client/src/components/FriendsBar/FriendsBar.tsx, client/src/components/MainContainer/Canvas.tsx, client/src/components/MainContainer/Diary.tsx, client/src/components/common/Socket.ts, client/src/components/common/atoms.ts, client/src/index.tsx, client/src/pages/MainPage.tsx, server/app.ts
사용자/날짜별  별도의 room에 입장해서 해당 room 사용자끼리 object 공유
1.방문중인 사용자의 ID 상태관리
2.diary탭에 입장시 방문중은 사용자의 ID와 현재연월일 8자리를 합쳐 roomName으로 지정
3.사용자/날짜별로 다른 object set에 접근할 수 있음
1.로그인하여 diary탭에 진입한다.
2. 여러날짜와 여러 사용자에 접근하여 각각 사용자/날짜별로 object가 관리되는지 확인한다.
-[6-11]
리액트 strictmode 사용시 현재 object가 2번 불러와지는 현상이 있습니다.
=> [BE] [6-11] 사용자/날짜별 별도의 room에서 diary 작성 구현 완료

client/src/components/MainContainer/GoalManager.tsx
`export GoalManagerWithContainer` → `export GoalManager`
=> [FE] [41] 목표 탭 export 변수명이 잘못되어있던 점 수정

server/src/api/task.ts
태스크 수정 API와 태스크 부분 수정 API가 구분되지 않았던 문제를 해결하기 위해 두 API의 요청 URL을 변경하였습니다.
추가로 태스크 부분 수정 API에서 `done`을 `false`로 변경하는 요청이 동작하지 않는 문제를 해결하였습니다.
`done`에 대한 수정을 요청하고 있는지 판별하는 부분에서 `if (done)` 조건문을 사용하여 `done`이 `false`일 때에도 해당 조건문 내의 명령이 수행되지 않아 발생한 문제였습니다.
조건문을 `if (done !== undefined)`로 수정하여 해결하였습니다.
- 태스크 수정 API
- 요청 URL : `/task/update/:task_idx`
- method : `PATCH`
- 태스크 부분 수정 API
- 요청 URL : `/task/status/:task_idx`
- method : `PATCH`
API 문서에도 해당 사항을 반영해 놓았습니다.
1. `/task?date=2022-12-01`을 통해 태스크 목록을 확인합니다.
2. `/task/update/14`를 통해 `idx = 14` 태스크에 대해 `title` 수정 요청을 전송합니다.
3. `/task?date=2022-12-01`을 통해 수정이 정상적으로 이루어졌음을 확인합니다.
4. `/task/status/14`를 통해 `idx = 14` 태스크에 대해 `done = false` 부분 수정 요청을 전송합니다.
5. `/task?date=2022-12-01`을 통해 수정이 정상적으로 이루어졌음을 확인합니다. …
=> [BE] [45] 태스크 수정 API, 태스크 부분 수정 API 수정

server/src/api/auth.ts, server/src/constants/index.ts
회원가입 시 프로필 이미지를 설정하지 않았다면 기본 프로필 이미지를 설정하도록 구현하였습니다.
추가로 기존에 DB에 존재하던 user 데이터 중 프로필 이미지가 null인 데이터의 프로필 이미지 또한 기본 프로필 이미지로 설정하였습니다.
1. 프로필 이미지를 설정하지 않은 채로 회원가입
2. 회원가입한 계정으로 로그인
3. `/user/me`를 통해 프로필 이미지가 `default_profile.png`로 설정되었음을 확인
[c87a78ad-40ae-44c4-9239-8921512d7f39.webm](https://user-images.githubusercontent.com/92143119/204989532-659eaa66-7035-48cf-9b91-a35d52a63f0d.webm)
1. 기본 프로필 이미지 파일을 상수로 지정
4. 프로필 이미지를 설정하지 않은 경우 기본 프로필 이미지로 설정
1. 프로필 이미지를 설정하지 않은 채로 회원가입을 완료합니다.
5. 회원가입 한 계정으로 로그인을 완료합니다.
6. `/user/me`를 통해 프로필 정보를 확인합니다.
- [34]
아직 파일명만 설정해 놓은 상태이고 기본 프로필 이미지 파일은 구하지 못했습니다.
구하는 대로 슬랙에 공유 드리겠습니다.
=> [BE] [34] 회원가입 시 기본 프로필 이미지 설정 구현

server/src/api/task.ts
태스크를 삭제하는 API를 구현하였습니다.
- 요청 URL : `/task/:task_idx`
- `task_idx` : 삭제하고 싶은 태스크
- 응답
- 태스크 삭제 성공 : `200`
- 존재하지 않는 태스크 : `404` (자신의 태스크 내에서 해당 태스크를 찾기 때문에 다른 사람의 태스크를 입력한 경우도 해당)
1. `/task?date=2022-12-20`을 통해 태스크 목록 확인
2. 존재하지 않는 `idx = 270` 태스크에 대한 삭제 요청
3. `404` 코드가 반환되는 것을 확인
4. `idx = 27` 태스크에 대한 삭제 요청
5. `/task?date=2022-12-20`을 통해 해당 태스크가 삭제되었음을 확인
[7dbf79f4-01c1-4605-9521-9146cec2a853.webm](https://user-images.githubusercontent.com/92143119/204970349-827d0be9-415a-4384-bc05-5250dca33cec.webm)
1. 태스크 삭제 API 구현
1. 로그인을 완료합니다.
6. 개발자 도구 콘솔에 아래의 명령어를 입력합니다.
```js
fetch('http://localhost:8000/api/v1/task/${task_idx}', {
method: 'delete',
headers: {
},
});
```
- [7-31]
=> [BE] [7-31] 태스크 삭제 API 구현

client/src/components/MainContainer/Diary.tsx, client/src/hooks/useCurrentDate.ts
useCurrentDate 훅에 날짜를 'YYYY-MM-DD'형식의 string으로 변환해주는 메소드를 추가했습니다
없다면 생략
1. useCurrentDate 훅에 날짜를 'YYYY-MM-DD'형식의 string으로 변환해주는 메소드를 추가했습니다
2. parameter(Date type)를 입력해줄경우 해당날짜를 변환시켜주며 아무값도 넘겨주지 않을 경우 currentDate에서 관리되는 recoil state 기준으로 값이 반환됩니다.
1.
-[42]
return 형식= 'YYYY-MM-DD'
=> [FE] [42] useCurrentDate 훅 dateToString 메소드 추가

client/src/components/MainContainer/Log.tsx
API URI를 최신 상태로 변경했습니다
현재 태스크 옮기기가 작동하지 않으며, 이 PR이 머지된 후 고쳐집니다.
=> [FE] [49] 로그 컴포넌트 - API URI 최신화

server/src/api/user.ts
프로필을 수정하는 API를 구현하였습니다.
프로필 수정 시 `username`과 `profileImg`만 수정 가능합니다.
- 요청 URL : `/user/me`
- `Request Body` : `{ username, profileImg }`
- method : `PATCH`
- 응답
- 프로필 수정 성공 : `200`
- `username`과 `profileImg`를 입력하지 않은 경우 : `400` (`profileImg: null`로 입력한 경우 회원가입 시와 마찬가지로 기본 프로필 이미지가 설정됨)
1. `/user/me`를 통해 프로필 확인
2. `profileImg`를 입력하지 않은 수정 요청
3. `400` 코드가 반환되는 것을 확인
4. `profileImg`를 `null`로 설정한 수정 요청
5. `/user/me`를 통해 수정이 정상적으로 이루어졌으며 `profileImg`의 경우 기본 프로필 이미지 파일로 설정된 것을 확인
[c10f2b48-fca0-44cd-a97e-4f047693ecd3.webm](https://user-images.githubusercontent.com/92143119/205063121-4f62cd63-9b21-4db9-8138-a06717d7d18e.webm)
1. 프로필 수정 API 구현
1. 로그인을 완료합니다.
6. 개발자 도구 콘솔에 아래의 명령어를 입력합니다.
```js
fetch('http://localhost:8000/api/v1/user/me', {
method: 'PATCH',
credentials: …
```
=> [BE] [4-4] 프로필 수정 API 구현

client/src/components/TaskModal/TaskModal.tsx
이제 태스크 생성 시 설정한 라벨이 정상적으로 요청에 포함됩니다.
[1903a1b3-329d-4625-b23f-55a26dd88e5b.webm](https://user-images.githubusercontent.com/55306894/205098527-bd11d4ce-7826-4e67-9f25-f3b3b3d48938.webm)
=> [FE] [51] 태스크 생성 요청에 라벨 포함

client/src/components/MainContainer/Log.tsx, client/src/components/TaskModal/TagInput.tsx, client/src/components/TaskModal/TaskModal.tsx
- 태그 목록, 태그 input focus 여부를 모달에서 관리하도록 수정
- tab 키를 통해 태그 input이 focus 되었을 때 자동완성 리스트가 렌더링되지 않던 문제 해결
1. 로그인을 완료하세요.
2. 태스크 FAB를 누르세요.
3. 태그를 등록하세요.
4. 라벨을 등록, 해제하면서 등록했던 태그가 깜빡이는지 확인하세요.
- [48] 태스크 모달 내 Tab 키로 이동 시 태그 검색결과 렌더링되지 않는 문제 → 해결
- [53] 태스크 모달 내 깜빡임 현상 → 해결
- 이제 태그 목록이 로그 컴포넌트에서부터 props로 전달됩니다.
=> [FE] [57] 태스크 모달 버그 수정

server/src/api/goal.ts, server/src/api/index.ts
목표를 조회할 수 있는 API를 구현하였습니다.
- 요청 URL : `/goal?date=${date}`
- `date` : 조회하고 싶은 날짜
- 응답
- `[ { idx, title, labelIdx,  goalAmount, currentAmount, over} ]` (목표 객체 배열)
- 날짜 미지정 : `400`
1. `/goal`을 통해 날짜 미지정 요청 전송
2. `400` 코드와 함께 날짜를 지정하라는 메시지가 반환됨을 확인
3. `/goal?date=2022-12-05`를 통해 목표 조회 요청
4. 목표 목록이 반환되는 것을 확인
[791cbb28-9a60-40a2-8ad1-f9733403cee3.webm](https://user-images.githubusercontent.com/92143119/205556678-382742aa-9319-4854-86c2-d136580036a2.webm)
1. 목표 조회 API 구현
1. 로그인을 완료합니다.
5. 주소창에 `http://localhost:8000/api/v1/goal?date=${date}`를 입력합니다.
- [8-2]
=> [BE] [8-2] 목표 조회 API 구현

client/src/components/FriendsBar/FriendsBar.style.ts, client/src/components/FriendsBar/FriendsBar.tsx, client/src/components/MainContainer/Diary.style.ts, client/src/components/MainContainer/Diary.tsx, client/src/components/MainContainer/Log.style.ts, client/src/components/MainContainer/Log.tsx, client/src/components/MainContainer/TaskItem.tsx, client/src/components/common/atoms.ts, client/src/pages/MainPage.tsx
친구의 프로필을 클릭하면 친구의 테스크를 표시하는 기능을 연결했습니다
- 상단 친구 바에 조회하고 있는 유저가 border 처리 되어 나타난다
- 친구 아이콘을 클릭 시 친구의 LOG를 조회한다.
- 조회하고 있는 친구의 아이디가 타이틀에 나타난다.
- 친구의 LOG 조회 시에는 완료 수정 삭제 버튼과 생성 버튼이 보이지 않는다.
**1. 전역변수 currentVisit을 { userId, isMe } 객체로 구체화했습니다. 아이디를 사용하기 위해서는 currentVisit.userId로 사용해주세요!!!** Diary 파일에서는 바꿔놨는데 빠뜨린 부분이 있을 수도 있으니까 확인해주세요
2. LOG / DIARY 탭 상단 아이디 표시
3. LOG / DIARY 탭 타이틀이 그림자 뒤에 보이는 문제 해결 및 css 조정
4-28. 친구의 프로필을 클릭하면 친구의 테스크를 표시한다.
60. LOG DIARY 탭 타이틀이 그림자 뒤에 보이는 문제
50. 태스크 이동 시 잔상이 남는 문제
- 캘린더가 연결되면 친구의 task 조회가 훨씬 수월해질 것 같습니다
- 다이어리 탭은 기능 완성되시면 css 조정 맡아서 하도록 할게요!
=> [FE] [4-28] 친구의 LOG 조회 기능 연결

server/src/api/goal.ts
목표를 수정할 수 있는 API를 구현하였습니다.
목표의 `date`는 수정이 불가능합니다.
해당 API를 통해 `date`에 대한 수정 요청을 하더라도 수정되지 않고 기존의 값이 유지됩니다.
- 요청 URL : `/goal/:goal_idx`
- Request Body
- `{ title: string, date: string(yyyy-mm-dd), labelIdx: number, amount: number, over: boolean }`
- 모두 필수 항목이지만 `date`의 경우 수정값을 입력하여도 기존 값이 유지됨
- method : `PUT`
- 응답
- 목표 수정 성공 : `200`
- 유효하지 않은 입력 : `400`
- 존재하지 않는 목표 및 라벨 : `404`
1. `/goal?date=2022-12-05`를 통해 목표 목록 확인
2. `labelIdx`를 입력하지 않은 목표 수정 요청
3. `400` 코드가 반환되는 것을 확인
4. 존재하지 않는 `idx=100` 목표에 대한 수정 요청
5. `404` 코드가 반환되는 것을 확인
[51388172-bd83-4abe-9e89-21927b161604.webm](https://user-images.githubusercontent.com/92143119/205705979-e9ba80e4-9307-4dbd-9c33-ea18bb7e25ce.webm)
1. `/goal?date=2022-12-05`를 통해 목표 목록 확인
2. `date = 2022-12-06` 수정값을 포함한 `idx = 5` 목표에 대한 …
=> [BE] [8-10] 목표 수정 API 구현

client/src/components/MainContainer/Canvas.tsx, server/app.ts, server/src/constants/index.ts
redis 클라우드에 diary canvas 도형을 저장하고 불러옵니다
기존과 동작은 같으며 중간에 redis에 데이터를 저장하고 불러오는 로직이 추가되었습니다.
1. redis 클라우드에 접속
2. socket room에 join시 처음접속했다면 redis에서 해당유저/일자에 해당하는 diary 도형 객체 로드하여 객체에 저장
3. 이후 자잘한 도형 추가/수정/삭제는 redis가 아닌 임시 데이터 객체에서 실행
4. socket room에서 leave시 마지막 사람이라면 임시 데이터를 해당유저/일자에 해당하는 key로 redis에 저장
1. 로그인하여 diary에 그림을 그린다
2. 접속해제후 dev 서버를 종료한다.
3. 다시 dev서버 실행 후 diary data가 남아있는지 확인한다.
- [6-3], [6-4]
=> [BE] [6-3] Diary canvas 도형 redis에 저장

server/src/api/goal.ts
목표를 삭제할 수 있는 API를 구현하였습니다.
- 요청 URL : `/goal/:goal_idx`
- 응답
- 목표 삭제 성공 : `200`
- 존재하지 않는 목표 : `404`
1. `/goal?date=2022-12-05`를 통해 목표 목록 확인
2. 존재하지 않는 `idx = 50` 목표에 대한 삭제 요청
3. `404` 코드가 반환되는 것을 확인
4. `idx = 5` 목표에 대한 삭제 요청
5. `/goal?date=2022-12-05`를 통해 목표가 정상적으로 삭제된 것을 확인
[d6d57a1b-d619-4703-b6fe-8eec721430bf.webm](https://user-images.githubusercontent.com/92143119/205708268-af1be33d-61ad-42e1-a35c-b952e7f265a5.webm)
1. 목표 삭제 API 구현
1. 로그인을 완료합니다.
```js
fetch('http://localhost:8000/api/v1/goal/${goal_idx}', {
method: 'DELETE',
headers: {
},
});
```
- [8-11]
=> [BE] [8-11] 목표 삭제 API 구현

server/src/api/goal.ts
1. 목표 조회 API 요청 시 반환되는 응답 중 `currentAmount`의 타입을 숫자로 변경하였습니다.
MySQL 내에서 `sum()`의 결과가 문자열로 반환되어 `currentAmount`의 타입도 문자열로 반환되는 상황이었습니다.
`cast()`를 통해 `unsigned`로 타입을 변경하여 해결하였습니다.
응답 및 요청 등의 내용에는 변경 사항이 없습니다.
2. `currentAmount` 계산 시 `done = true`인 태스크의 내용만 반영하도록 수정하였습니다.
태스크에 라벨을 설정하더라도 해당 태스크를 완료하기 전까지는 목표에 반영되지 않습니다.
1. `/goal?date=2022-12-05`를 통해 목표 조회 요청
2. `currentAmount`의 값이 숫자로 반환되는 것을 확인
[ab81bc20-add7-4a78-94b0-bb49a8f9225b.webm](https://user-images.githubusercontent.com/92143119/205827916-4e3dd215-ded2-4ebe-aab4-38a876a7ffbd.webm)
1. 목표 조회 API의 `currentAmount` 타입 수정
2. `currentAmount` 계산 시 `done = true`인 태스크만 반영하도록 수정
1. 로그인을 완료합니다.
3. 주소창에 `http://localhost:8000/api/v1/goal?date=${date}`를 입력합니다.
- [63]
=> [BE] [63] 목표 조회 API 수정

client/src/components/FriendsBar/FriendsBar.style.ts, client/src/components/FriendsBar/FriendsBar.tsx, client/src/components/MainContainer/Calendar.style.ts
친구Bar의 프로필사진에서 우클릭하면 프로필조회와 친구삭제가 가능한 모달이 생성됩니다
1. 우클릭시 선택한 친구의 id 상태로 관리
2. 선택한ID의 친구 아래 프로필조회/친구삭제가 가능한 모달 생성
3. 이외 영역을 클릭하면 선택한 친구 state를 null로 변경
1.로그인하여 친구창의 친구프로필사진 위에서 우클릭을 한다.
-[4-24]
=> [FE] [4-24] 친구프로필조회/삭제 모달 생성

server/src/api/task.ts
태스크 삭제 시 친구가 태스크에 이모티콘을 남긴 경우 삭제가 불가능한 버그를 수정하였습니다.
task_social_action의 데이터를 삭제하지 않아 발생한 문제였습니다.
요청 및 응답 등에 대한 변경 사항은 없습니다.
1. `/emoticon/task/161`을 통해 `idx = 161` 태스크에 이모티콘이 남겨진 것을 확인
2. `idx = 161` 태스크 삭제 요청
3. `/emoticon/task/161`을 통해 존재하지 않는 태스크라는 메시지를 확인하여 태스크 삭제가 이루어진 것을 확인
[2c824b19-a473-4ca9-a928-60c4567fa203.webm](https://user-images.githubusercontent.com/92143119/206129787-0ddc5185-4487-471e-9dda-43fe80460938.webm)
1. task_social_action을 삭제하지 않아 task 삭제가 불가능했던 버그 수정
1. 로그인을 완료합니다.
```js
fetch('http://localhost:8000/api/v1/goal/${goal_idx}', {
method: 'DELETE',
headers: {
},
});
```
- [71]
=> [BE] [71] 태스크 삭제 API 수정

server/src/api/calendar.ts
월 단위로 일별 평균 목표 달성률을 조회할 수 있는 API를 구현하였습니다.
목표 달성률은 아래의 조건에 따라 계산하였습니다.
- 목표 달성률 범위 : 0 이상 1 이하
- 목표가 존재하지 않는 경우 : `0`
- 목표의 `over = true`인 경우 (설정한 값 이상의 목표를 달성해야 하는 경우)
- `현재 값 / 목표 값`
- 목표 값보다 높은 값을 달성한 경우 : `1`
- 목표의 `over = false`인 경우 (설정한 값을 넘지 않아야 하는 목표의 경우)
- 설정한 값을 넘지 않은 경우 : `1`
- 설정한 값을 넘은 경우 : `0`
해당 API의 요청 및 응답 정보입니다.
- 요청 URL : `/calendar/goal?year=${year}&month=${month}`
- `year` : 조회하고 싶은 연도
- `month` : 조회하고 싶은 달
- 응답
- `float[]` (평균 목표 달성률 배열)
- 배열의 크기는 요청한 달의 일수입니다.
- `배열의 0번 index = 1일의 정보`, ... , `배열의 30번 index = 31일의 정보`
- 연도 및 달 미지정, 잘못된 달 입력 : `400`
1. 연도 및 달 미지정 요청
2. `400` 코드와 함께 올바른 연도를 입력하라는 메시지가 반환되는 것을 확인
3. 달 미지정 요청
4. `400` 코드와 함께 올바른 달을 입력하라는 메시지가 반환되는 것을 확인
5. `month = 13` 입력 요청
6. `400` 코드와 함께 올바른 달을 입력하라는 메시지가 …
=> [BE] [5-5] 일별 평균 목표 달성률 조회 API 구현

server/src/api/task.ts
태스크 수정 시 빈 문자열과 `null`에 대한 입력이 처리되지 않는 버그를 수정하였습니다.
입력된 값이 `undefined`인지 체크하는 과정에서 `!value`라는 조건을 사용하여 위의 값도 `undefined`와 똑같은 처리가 이루어져 발생한 문제였습니다.
해당 조건문을 `value === undefined`로 변경하여 해결하였습니다.
추가로 빈 문자열이 입력된 경우 `null`로 취급하여 처리하도록 수정하였습니다.
1. `idx = 14` 태스크에 대하여 `location = ''` 수정 요청
2. `/task?date=2022-12-01`을 통하여 빈 문자열이 `null`로 취급되어 정상적으로 수정된 것을 확인
[b72fb483-edb4-4af3-bdbb-df33505e20d6.webm](https://user-images.githubusercontent.com/92143119/206149277-2428db71-3182-45f0-96b6-a9e89e637d3c.webm)
1. 빈 문자열, null 입력 처리
1. 로그인을 완료합니다.
3. 개발자 도구 콘솔에 아래의 명령어를 입력합니다.
```js
fetch('http://localhost:8000/api/v1/task/${task_idx}', {
method: 'PATCH',
headers: {
},
${수정하고 싶은 항목}: ${수정할 값}
}),
});
```
- [73]
=> [BE] [73] 태스크 수정 API 수정

server/src/api/task.ts
- 이제 13:00에 시작하고 11:00에 종료되는 태스크는 만들 수 없습니다.
=> [BE] [65] 태스크 생성 요청 시 종료 시각이 시작 시각보다 앞설 경우 400 반환

client/src/components/MainContainer/GoalManager.style.ts
- Progress Bar가 과도하게 넘실대지 않게 조정했습니다.
[689bd606-1273-498d-bec3-da731a19466c.webm](https://user-images.githubusercontent.com/55306894/206155504-d19f066c-0712-46d9-b9b8-7da8214d904b.webm)
=> [FE] [8-20] 목표 탭 Progress Bar 스타일 개선

client/src/components/MainContainer/Log.tsx, client/src/components/MainContainer/TaskItem.tsx, client/src/components/TaskModal/TaskModal.tsx, client/src/types/type.d.ts
- 테스크 수정 API 연결을 진행했습니다.
- TaskModal에서의 수정 기능을 구현했습니다.
- 모든 요소가 수정 가능합니다. 위치와 라벨의 삭제도 가능합니다. 수정된 값은 바로 화면에 반영됩니다.
1. Log 컴포넌트의 isEditModalOpen 값으로 관리
2. TaskModal의 props으로 현재 열려있는 currentTask 정보를 전달합니다. 해당 값이 null인 경우 생성 모달로서, 해당 값이 존재하는 경우 수정 모달로서 기능하도록 분기 처리했습니다.
3. LabelData 인터페이스 내 인덱스 값이 labelIdx가 아닌 idx로 설정되어 있던 문제를 수정했습니다.
4. 라벨 생성 시의 isPublic 기본값을 true로 변경했습니다.
- 7-8
=> [FE] [7-8] 테스크 수정 API 연결 및 모달 기능 구현

client/src/components/MainContainer/Calendar.tsx, client/src/components/MainContainer/Diary.tsx, client/src/components/MainContainer/GoalManager.tsx, client/src/components/MainContainer/Log.tsx, client/src/components/MainContainer/MenuSelector.tsx, client/src/components/MainContainer/TaskItem.tsx, client/src/components/common/atoms.ts
- LOG GOAL 탭 캘린더 API 를 연결했습니다
- url 이동으로 화면 전환 시 메뉴 셀렉터가 수정되지 않는 문제를 해결했습니다.
- 연결된 달력을 확인할 수 있습니다.
- 이제 어떤 방법으로 탭 이동시에도 메뉴 셀렉터가 올바르게 작동합니다.
1. API 연결
2. 메뉴 셀렉터 값을 전역 변수로 관리합니다
5-1.
38.
- 목표 달력 API 오류가 발견되었습니다.
- Task 생성 시에 달력이 갱신되는 로직을 개선 중입니다.
=> [FE] [5-1] LOG, GOAL 탭 캘린더 API 연결 / 메뉴 셀렉터 로직 수정

client/src/components/MainContainer/Canvas.tsx, client/src/components/MainContainer/Diary.tsx, client/src/components/common/Socket.ts, server/app.ts
배경로딩, Socket Room join, 현재 존재하는 도형 loading 순서를 동기화했습니다.
없다면 생략
1. 이제 다이어리탭에 진입하면 제일 먼저 배경화면을 불러옵니다
2. 배경화면 로딩이 끝나면 소켓 Room에 진입합니다
3. 소켓Room에 진입하면 클라이언트에 완료신호를 보냅니다
4. 클라이언트는 신호를 받으면 초기 도형 정보를 요청합니다
1.
-[6-3]
=> [FE/BE] [6-3] Diary 초기 도형 로딩 동기화

client/src/components/MainContainer/Calendar.style.ts, client/src/components/SignupMenu/SignupMenu.style.ts, client/src/components/SignupMenu/SignupMenu.tsx, client/src/components/TopBar/Clock/Clock.style.ts, client/src/components/TopBar/TopBar.style.ts
- 회원가입 페이지가 짤리는 문제를 해결했습니다.
- 컴포넌트 타이틀이 그림자 뒤에 보이는 문제를 해결했습니다.
- 에러가 발생할 경우에만 상황에 따라 적절하게 늘어납니다.
<br>
- 타이틀이 정상적으로 표시됩니다.
- 아마 drawer 클릭시 dimm보다 타이틀이 위에 보이는 문제 때문에 z-index를 수정해주신 것 같은데 dimm보다 아래에 표시되도록 수정했습니다.
17
=> [FE] [17] 회원가입 페이지 디자인 조정

client/src/components/MainContainer/GoalManager.tsx
- `over`가 `false`일 때 body에 제대로 반영이 되지 않던 문제를 해결했습니다.
=> [FE] [84] 목표 생성 요청 body에 무조건 over: true가 담기는 문제 해결

server/src/api/calendar.ts
친구의 일별 태스크 존재 여부 조회 시 친구의 비공개 태스크가 포함되어 캘린더에는 존재하는 것으로 표시되지만 해당 날짜 조회 시 태스크가 조회되지 않는 문제가 있었습니다.
태스크 존재 여부 결정 시 공개 태스크만을 고려하도록 SQL을 수정하여 해결하였습니다.
기타 변경 사항은 없으며 응답 및 요청 등에 대한 정보는 아래 PR과 동일합니다.
- https://github.com/boostcampwm-2022/web19-Boostart/pull/190
- 왼쪽 화면 : `pikachu`
- 오른쪽 화면 : `pikachu`와 친구 관계인 `sy`
1. 오른쪽 화면 : `/friend`를 통해 `pikachu`와 친구 관계임을 확인
2. 왼쪽 화면 : `pikachu`에게 `2022-12-09`에 비공개 일정만 존재하는 것을 확인
3. 오른쪽 화면 : `/calendar/task/pikachu?year=2022&month=12`를 통해 `2022-12-09`의 태스크 존재 여부가 `false`인 것을 확인
[5237802d-cf3d-44f5-8db8-0b8e44b84266.webm](https://user-images.githubusercontent.com/92143119/206507071-e639cb1f-2c4d-4b35-a276-d776c4131cfd.webm)
1. 친구의 태스크 존재 여부 조회 시 공개 태스크만 포함되도록 수정
1. 로그인을 완료합니다.
4. 주소창에 `http://localhost:8000/api/v1/calendar/task/${user_id}?year=${year}&month=${mon …
=> [BE] [87] 친구의 일별 태스크 존재 여부 조회 API 수정

client/src/components/MainContainer/Calendar.tsx, client/src/components/MainContainer/Map.tsx, client/src/components/common/atoms.ts
- MAP 탭 캘린더 연결은 #187 에서 해주셨네요 ㅎㅎ
- LOG 외의 탭 접근 시 잘못 표시될 때가 있는 문제를 해결했습니다.
- 새로고침 시에도 올바르게 표시됨
- 맵 탭에서는 테스크 존재 여부를 표시함
- 5-1
- 다이어리 캘린더는 레디스로 확인해야 돼서 제가 연결하지 못했습니답,,
=> [FE] [5-1] 캘린더 타이밍 오류 수정

client/src/components/TaskModal/TaskModal.tsx
- 테스크 수정 모달을 구현하면서 테스크 생성 시 값이 True로 고정되고 / 수정 시 기존의 isPublic 값으로 고정되는 문제가 있었습니다.
- defaultChecked 사용 시 값을 보내기 직전에 isPublic 값이 defaultChecked로 다시 바뀌는 것 같습니다.
- 간단하게 해결할 수 없어서 일단 생성, 수정 시 모두 defaultChecked가 설정되어 있지 않는 걸로 임시 수정했습니다. ( -> 모달이 열릴 때 isPublic이 체크되어 있지 않는 상태로 시작합니다 )
86
=> [FE] [86] 테스크 모달의 공개 여부를 변경할 수 없는 문제

client/src/components/Drawer/Drawer.style.ts, client/src/components/Drawer/Drawer.tsx
- 프로필 수정 API 연결
- 기본 로직은 회원가입 창과 똑같습니다. 
4-2
- 기본 로직은 회원가입을 참고했습니다 API단도 회원가입을 참고해주시면 좋을 것 같습니다.
- axios로 해도되는데 뭔가 안될까봐 회원가입에서 사용한 fetch 방법을 그대로 사용했습니다 ( 회원가입은 POST고 여기는 PATCH인데 동일하게 사용 가능하겠죠..? ) 
- 업로드 API가 완성이 안돼서 연결 코드만 작성해놓았습니다
- null 일 때는 사진 제거로 하기로 했는데 지금 기본 이미지로 돌아가는 버튼이 없어서 ( 파일 선택 버튼 -> 취소 시 그냥 이전 사진이 그대로 남아있음 ) null로 들어갈 일은 아마 없을 것 같습니다.
- 파일은 FormData 형식으로 보내야되는데 undefined는 FormData에 붙일 수가 없어서 사진을 변경하지 않을 시에는 아예 profileImg 칼럼이 없는 상태로 들어갑니다
=> [FE] [4-2] 프로필 수정 API 연결

client/src/components/MainContainer/Calendar.tsx
- 친구의 LOG / MAP 탭 캘린더 연결
- 친구에 따라 LOG / MAP 탭의 상태가 테스크 존재 여부로 표시됩니다.
5-10
- 목표 탭은 아직 API 완성이 안돼서 연결이 안됐습니다.
- private 테스크도 존재 여부에 포함되는 문제가 있습니다. 87번 백로그로 등록했습니다.
=> [FE] [5-10] 친구의 LOG / MAP 탭 캘린더 연결

server/src/api/calendar.ts
월 단위로 일별 평균 목표 달성률을 조회할 수 있는 API를 구현하였습니다.
목표 달성률은 아래의 조건에 따라 계산하였습니다.
- 목표 달성률 범위 : 0 이상 1 이하
- 목표가 존재하지 않는 경우 : `0`
- 목표의 `over = true`인 경우 (설정한 값 이상의 목표를 달성해야 하는 경우)
- `현재 값 / 목표 값`
- 목표 값보다 높은 값을 달성한 경우 : `1`
- 목표의 `over = false`인 경우 (설정한 값을 넘지 않아야 하는 목표의 경우)
- 설정한 값을 넘지 않은 경우 : `1`
- 설정한 값을 넘은 경우 : `0`
친구의 목표 달성률은 아래의 이유로 비공개 태스크의 라벨 정보도 포함하여 계산하였습니다.
1. 목표는 공개 여부를 설정할 수 없으므로 항상 공개인 상태
2. 비공개 태스크의 라벨 정보를 목표에 포함하지 않을 경우 목표 달성률 측정이 애매해지고 친구의 목표 달성률 정보는 부정확한 정보가 됨
해당 API의 요청 및 응답 정보입니다.
- 요청 URL : `/calendar/goal/:usre_id?year=${year}&month=${month}`
- `user_id` : 조회하고 싶은 친구의 아이디
- `year` : 조회하고 싶은 연도
- `month` : 조회하고 싶은 달
- 응답
- `float[]` (평균 목표 달성률 배열)
- 배열의 크기는 요청한 달의 일수입니다.
- `배열의 0번 index = 1일의 정보`, ... , `배열의 30번 index = 31일의 정보`
- 본인에 대한 요청 : …
=> [BE] [4-33] 친구의 일별 평균 목표 달성률 조회 API 구현

client/src/components/MainContainer/Map.tsx, client/src/constants/index.ts, server/app.ts
map 탭에서 친구의 task를 동시에 확인할 수 있습니다
없다면 생략
- task 위치 마커
1. 기본적으로 본인의 task 위치를 조회합니다 
2. 방문중인 페이지가 나의 페이지가 아니라면 선택된 친구의 task 위치를 함께 조회합니다
3. 친구의 task는 노란색으로, 나의 task는 보라색으로 마커를 표시합니다.
-task list
1. 좌측에는 본인의 task list가, 우측에는 친구의 task list가 표시됩니다.
2. 위치정보를 가진 task가 해당일자에 존재하지 않는다면 list도 표시되지 않습니다.
3. 나와 친구 둘다 위치정보를 가진 task가 없다면 중앙에 '위치정보를 가진 일정을 추가해주세요' 라는 문구를 나타냅니다
- map 영역 설정
1. 초기에는 조회된 모든 task를 확인 가능한 크기로 지도 영역을 설정합니다.
2. 좌측 목록 아래 전체보기를 클릭시 나의 일정 전체를 확인가능한 영역으로 설정합니다.
3. 우측목록 아래 전체보기를 클릭시 친구의 일정 전체를 확인가능한 영역으로 설정합니다.
4. 나와 친구 둘다 task가 있을 경우 중앙 상단에 두 사람 모두의 task를 포함하는 영역으로 전환하는 전체보기 버튼이 생성됩니다.
-[9-3]
=> [FE] [9-3] map 탭에서 친구의 task 동시 확인 가능

client/src/components/MainContainer/Calendar.style.ts, client/src/components/MainContainer/Calendar.tsx
- 캘린더 로고의 크기를 조정했습니다.
- 91% 등 과 같이 세밀한 값도 눈으로 확인할 수 있습니다.
로고의 크기가 글자 모양을 넘게 설정되어 있어, 90퍼 정도가 넘으면 색이 꽉차 보이는 오류가 있었습니다. 이를 조정했습니다.
91
=> [FE] [91] 캘린더 로고의 크기가 커 퍼센트가 높거나 낮은 값은 올바르게 표시되지 않는 오류

client/src/components/common/Socket.ts
- 소켓 재연결 시 기존 연결을 끊도록 개선했습니다.
```
-- 서버와 연결되어 있는 소켓 목록 --
[Map Iterator] {
'91SprlxW0ybLji8VAAAD',
'5g7Tr0OiVxrf5bZ_AAAF',
'6zyeODOKaJvU2QeMAAAH',
'f-6SMSUXIPm7W0SdAAAJ'
}
-- 접속중인 유저의 소켓 아이디 목록 --
{ '32': 'f-6SMSUXIPm7W0SdAAAJ' }
```
```
-- 서버와 연결되어 있는 소켓 목록 --
[Map Iterator] { 'AIu6tUmHPuPRQJ3wAAAf' }
-- 접속중인 유저의 소켓 아이디 목록 --
{ '8': 'AIu6tUmHPuPRQJ3wAAAf' }
```
=> [FE] [92] 불필요한 소켓 연결 해제

server/src/api/user.ts, server/src/types/index.d.ts
프로필 수정 시 새로 지정한 프로필 이미지를 저장하지 않는 버그를 수정하였습니다.
프로필 수정 모달에서 보내는 요청의 형태는 다음과 같습니다.
- 프로필 이미지를 변경하지 않았을 경우
- `req.body = { username }`
- `req.files = null`
- 프로필 이미지를 변경하였을 경우
- `req.body = { username }`
- `req.files = ${설정한 파일의 정보}`
따라서 `req.files`의 존재 여부에 따라 프로필 이미지 변경 여부를 결정하였습니다.
기존 프로필 이미지를 삭제하고 기본 프로필 이미지 설정을 원하는 경우에 대해서는 추가적인 컬럼 설정 등의 협의가 필요할 것 같습니다.
추가로 프로필 이미지를 변경한 경우 기존 프로필 이미지 파일은 삭제하도록 구현하였습니다.
기타 변경 사항은 없으며 요청 및 응답에 대한 내용은 아래 PR과 동일합니다.
- https://github.com/boostcampwm-2022/web19-Boostart/pull/132
1. 로그인을 완료한 뒤 우측의 햄버거 버튼을 클릭합니다.
2. 우측 상단의 프로필 수정 버튼을 클릭합니다.
3. 변경할 프로필 이미지를 설정합니다.
4. `PROFILE CHANGE` 버튼을 클릭한 뒤 새로고침하여 변경된 프로필을 확인합니다.
[ce8f7ca0-bcae-46b5-b30e-0e98fb564b16.webm](https://user-images.githubusercontent.com/92143119/206887432-4558a0a5-5657-4c73-8e6a-579a4bcf733c.webm)
1. …
=> [BE] [59] 프로필 수정 API 수정

client/src/components/MainContainer/GoalManager.tsx, client/src/components/common/utils.ts, server/src/utils/auth.ts
- 클라이언트가 API 응답으로 401이나 403을 받을 경우 새로고침이 일어나며, 훅에 의해 로그인 페이지로 리다이렉트됩니다.
1. 로그인이 필요한 요청을 감싸 인증 실패 에러를 처리하는 함수를 작성했습니다.
2. 토큰 만료 시 새로고침이 적용되도록 수정했습니다.
- 목표 탭에만 적용
=> [FE] [105] 토큰 만료 시 새로고침
